### ISSUE TITLE
Adding Support for Appnexus Aliases

### ISSUE THREAD

**Issue by ehoch** [prebid/prebid-server#11]
Not sure if you guys want this on the server-side or client-side, but there's currently no support for the various appnexus aliases adapters in here.

**Comment by bokelley** [comment]
There is support for DistrictM right now; we're trying to decide whether it makes sense to have each additional one hardcoded or not, to your point.

**Comment by pboisso** [comment]
We have this need too.  Multiple AppNexus aliases working fine on the client side, but can't send more than the real 'appnexus' one to server.  Would be nice to be able to send client-side aliases to prebid server as well.

**Comment by dbemiller** [comment]
In prebid.js, there are two ways of setting aliases. I'll call these **static** and **dynamic**

**static** aliases are defined by adapters in the code, like [this](https://github.com/prebid/Prebid.js/blob/master/modules/appnexusBidAdapter.js#L33)

**dynamic** aliases are defined by publishers, through `$$PREBID_GLOBAL$$.aliasBidder`

Two things I'd like to note

- These two cases are functionally independent, unless the dynamic aliases conflict with the static ones.
- Everything that can be done with static aliases can also be done with dynamic ones.

As a general rule, it's not great practice to implement two features where one is a subset of the other. Some exceptions exist, of course: for example, if the less powerful one handles most of the simple uses, and is significantly "better" somehow (more convenient, efficient, etc). 

In this case, I'm having a hard time seeing the value in static ones. Since `prebid.js` already knows about all the static aliases, so we could implement the the `prebidServerBidAdapter` to send them in the Request. It's no more or less convenient for Publishers.

Static aliases would also make the request size marginally smaller... but I don't think it's likely to make such a huge difference, since most requests use few (if any) aliases. As long as the client doesn't send _all_ the known aliases, the performance improvement should be modest.

Lastly, I'll note that if we implemented both of these things, the least surprising behavior (in my opinion) would be if dynamic aliases took precedence over static ones. This would let callers have the final word on the auction behavior.

All that in mind: My initial plan is to implement dynamic aliases _only_.

I'll keep in touch with the engineer who's going to update the `prebidServerBidAdapter` to use OpenRTB. If it turns out to be more difficult than I imagine for JS to send the aliases, I'm not strongly opposed to adding static alias support. I just believe it's better to omit features which don't add enough value to justify their weight.
