### ISSUE TITLE
Context deadline exceeded related to timeout

### ISSUE THREAD

**Issue by ah-tappx** [prebid/prebid-server#1150]
Hello,
Some of our publishers have experienced issues receiving responses like the following:
`{"id":"8d72b60b-847e-4486-a60b-386946fad3d3","ext":{"errors":{"tappx":[{"code":999,"message":"context deadline exceeded"}]},"responsetimemillis":{"tappx":449},"tmaxrequest":500}}`

It seems that this happens when our server responds in a similar time with tmax value. This also seems to be affected by the publisher location. We would like to understand this error and try to solve it.

Thank you.

**Comment by SyntaxNode** [comment]
This error indicates that Tappx took longer than 450ms (approx) to respond back to the PBS server and was cancelled via a timeout. In Go, timeouts are implemented by "contexts" and apparently we don't have a nicely formatted error message.

If a bid needs to be cached, PBS reserves 50ms of auction time for a synchronous write to the cache service. With a little bit of rounding precision, that's why you're seeing 449 instead of something closer to the tmax of 500.

Makes sense to be related to publisher location as that is likely correlated to user location and the latency from those data centers back to Tappx might be longer depending on if Tappx has a data center close by.

**Comment by bretg** [comment]
@ah-tappx - do you accept this solution?

**Comment by ah-tappx** [comment]
Thank you. We'll keep in mind this considerations and try to work with this. If new issues related with this come up we will contact again.
