### ISSUE TITLE
Prebid Server Price Floor Feature

### ISSUE THREAD

**Issue by bszekely1** [prebid/prebid-server#1162]
# Overview
The document describes the Prebid Server implementation of the Price Floor Feature as defined [here](https://github.com/prebid/Prebid.js/issues/4273). Prebid Server will contain its own set of requirements given the additional flexibility PBS has to execute code in a server-side environment.

Intended workflow will remain the same in PBS as in pbjs:

1. Publisher signs with a Price Floor provider
2. Price Floor provider makes a JSON file available with the data
3. Publisher configures Prebid to resolve and enforce the price floor

PBS should support Prebid.js, Prebid Server, and Prebid SDK.

Please see the [Product Requirements Document (PRD)](https://docs.google.com/document/d/1YAt00RfQaU2Ugciqw1LnirLgjyUz9ibfyjfxWUHR_P0/edit#) for detail.

**Comment by hhhjort** [comment]
Not really specified above, but my feelings towards account scope data is as follows:

For options that are controlled by the publisher or by the PBS host's business logic, it is best to use an object stored directly in the request, and have that data filled in by the stored request backend. That will then hook the configuration into the existing publisher config system rather than adding a second location where some publisher configs will live.

For options that the PBS host will need to control directly without option for the publisher to override (for example account white/blacklists), PBS configuration option rather than request object.

So for the above flags, I would recommend all the flags be settable in the request, which would by default allow all of them to be auction specific in theory, while the stored request solution could limit some to an account level setting. At least outside of a publisher overriding what the stored request system supplied using a properly crafted request.

**Comment by albertmolinermrf** [comment]
Is the list of supported fields for floor schema final? For example, the examples contain "impId" and "imp.id", but none is explicitly listed there. Additionally, are the values case-sensitive? If so, can we print them explicitly?

Is there an expected resolution algorithm when multiple keys are match? First wins, last wins, most specific wins...

**Comment by bszekely1** [comment]
@hhhjort Thank you, i added better definition in the description to keep context of host-wide flags or stored request level flags. If you have any feedback, I am open to suggestions.

@albertmolinermrf 
> Is the list of supported fields for floor schema final?

The list is not final. This is simply in the intent to implement phase and has not started. The idea is to make the system flexible to fit most use cases. In this first pass we wanted to start with some basic fields that made sense. We didn't want to overload the development from the start.

>  are the values case-sensitive?

no. Following what we are doing in js, all rules and processing should be treated as lower case, even if sent as upper case. I added that requirement as point 24.

> If so, can we print them explicitly?

See point 20 in the requirements for the list of defined supported fields. I left out impId. Thanks for the heads up.
 
> Is there an expected resolution algorithm when multiple keys are match? First wins, last wins, most specific wins...

The idea here is that there should not be two matches. The floor provider (or publisher if setting rules manually) should avoid having duplicate rules. It is impossible for rules to collide if they are all unique. For non-unique rules, the behavior would be unexpected results.

**Comment by bretg** [comment]
Note that this feature should be implemented using the Modularity architecture https://github.com/prebid/prebid-server/issues/1734

**Comment by pm-jaydeep-mohite** [comment]
Hi @bretg, 
Could you please help us to know if  anyone is working on this feature?
We would like to understand PRD for Floor feature along with Modular approach.
Can we  get into call to discuss this feature to be on same page?

**Comment by bretg** [comment]
Floors are live in PBS-Java as of 1.87

**Comment by afewcc** [comment]
Hello! Are floors also live in PBS-go ? Can this be closed ? Thx

**Comment by bretg** [comment]
Good call @afewcc - this was indeed done in PBS-Go by the Pubmatic team last year over a series of PRs. Closing.
