### ISSUE TITLE
Districtm metrics

### ISSUE THREAD

**Issue by bastianb-yl** [prebid/prebid-server#1193]
We use Influxdb for metrics. In our own tracking we see districtm, but not in the metrics. The meters are there but have no data. Since districtm uses the appnexus adapter, i could assume the metrics also use appnexus as identifier.
But since there are meters for districtm created in influx, i'm a little confused. Is this just a misconfiguration on our end or are the districtm metrics not working at all?
Can someone confirm districtm metrics working and maybe give me a hint?

**Comment by SyntaxNode** [comment]
Which metrics are you looking at? I'm able to see distinct DistrictM vs AppNexus metrics for things like request count and errors in our data centers. We're using Prometheus, but the data should be identical.

I'm also curious if your traffic is OpenRTB or Legacy?

**Comment by bastianb-yl** [comment]
It's traffic from AMP sites, using the /openrtb2/amp endpoint.

**Comment by SyntaxNode** [comment]
Gotcha. There is no DistrictM adapter for OpenRTB requests. We (AppNexus / Xandr) have the alias setup in our host config, but the adapter will still log metrics under the `appnexus` adapter label. We hardcode a DistrictM alias for Legacy requests and that's why you're seeing metrics generated for them... but please don't use Legacy requests. That's on our list of things to axe soon(ish).

We'll also be reevaluating is our alias approach is sufficient. Comments are welcomed.

**Comment by bastianb-yl** [comment]
Ah, the soonish to do list. I have that too ;)

Thanks for your reply. At least now we know why this is happening.
