### ISSUE TITLE
Questions on some features and configurations

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#1276]
Hi Appnexus Prebid team,

We have our Brightroll adapter, currently running on Prebid server successfully. Currently have one publisher using it as well. We have plan for more publishers to onboard in near future.

We would like to discuss a few features on Prebid side on that.
1. How do we configure different endpoints based on different regions(APAC/EMEA/EAST/WEST)?
2. There is publisher specific blocked items need to configure(like battr, bcat, badv in OpenRTB) for each publisher. Currently I have hardcoded in the brightroll adapter code for the one publisher we onboarded. So if we need to add a new publisher, need to change code to add hardcode the blocked items for that publisher. Usually in a Exchange/SSP world, publishers usually configure those fields in Ex/SSP system. 
Is there a way Prebid framework can support this?  Currently Rubicon Prebid Server added this feature in their Java framework, which helps us just need to configure those values for different publishers in adapter's configuration file. Is it possible to have similar support in APN Prebid server/framework as well? 
Please let me know if it is not clear. We can setup a quick meeting as per your convenience if required.

Thanks
Smitha

**Comment by SyntaxNode** [comment]
Hi Smitha,

> How do we configure different endpoints based on different regions(APAC/EMEA/EAST/WEST)?

Please contact Xandr support at prebid-server@xandr.com for questions specific to their hosting.

> There is publisher specific blocked items need to configure ... Is there a way Prebid framework can support this?

Yes. There is a feature to allow adapters to parse a json blob of whatever config settings they would like. This is currently used by a few adapters, including Beachfront. You'll find the config object here: https://github.com/prebid/prebid-server/blob/f1f2b094a9c202300087a3c9bcc99c06e711e9c6/config/config.go#L245

I think it makes sense to put out a PR to use this in the Brightroll adapter and work with Xandr (or any other host you'd like to work with) to configure it in their environment.

**Comment by smithaammassamveettil** [comment]
@SyntaxNode 
Regarding the configuration specific to each publisher, I searched to find its usage in different adapters to know how to use it. But couldnt find this object ' ExtraAdapterInfo ' used anywhere in the prebid/prebid-server repo. Even searched BeachFront adapter to see how its being used. 
Can you please help to point to the exact location where I can reference to know how to use it? Is there any documentation on this?

**Comment by SyntaxNode** [comment]
Absolutely. Unfortunately we don't have documentation on this yet. I know we're behind across the board on docs for this repo. That's something we're starting to address and I ask for your patience as that is improved.

For now...

1) The ExtraAdapterInfo string is passed into the Beachfront adapter constructor here:
https://github.com/prebid/prebid-server/blob/9e7e1cf306a307ebd48f59a36c4669276af11703/exchange/adapter_map.go#L94

2) Beachfront is parsing the string here. It's just a string so you can use whatever data format you like, but I'd personally recommend using JSON since it's what the rest of the project is using for configs.
https://github.com/prebid/prebid-server/blob/9e7e1cf306a307ebd48f59a36c4669276af11703/adapters/beachfront/beachfront.go#L686

**Comment by SyntaxNode** [comment]
@smithaammassamveettil Does this answer your question?

**Comment by bretg** [comment]
@smithaammassamveettil ?

**Comment by smithaammassamveettil** [comment]
Will close it for now.
