### ISSUE TITLE
Empty httpcalls array for bidder.

### ISSUE THREAD

**Issue by moteus** [prebid/prebid-server#1344]
I just try to make a request for the Pubnative bidder with test flag on, but got a response like
```JSON
{
  "id": "***",
  "ext": {
    "debug": {
      "httpcalls": {
        "pubnative": [] <------ here empty array.
      },
      "resolvedrequest": {<HERE MY REQUEST>}
      }
    },
    "responsetimemillis": {
      "pubnative": 315
    },
    "tmaxrequest": 800
  }
}
```
I suspect this is because of the pubnative adapter [set the test flag to 0](https://github.com/prebid/prebid-server/blob/master/adapters/pubnative/pubnative.go#L86)

**Comment by SyntaxNode** [comment]
That seems very likely, yes. I'll discuss this with the team early next week. Perhaps we should record the value of the test flag before the adapter does its thing and modifies the request.

**Comment by bretg** [comment]
@fhartwig - would like to understand why your adapter is ignoring/overriding the test flag. In general, the expected behavior for bidders would be to discount impressions when 'test' is specified. If the aim is to avoid test requests to your bidder, I would think your adapter would just invalidate the auction rather than ignoring the explicit signal that this isn't a normal user.

Note that this relates tangentially to https://github.com/prebid/prebid-server/issues/745 -- where we define a separate flag for "debug" vs "test". It's an important distinction:
- test means this isn't a real user. the bidder probably shouldn't charge for the bid.
- debug means it could be a real user, but the publisher wants the extra tracing for confirmation or troubleshooting

@SyntaxNode - is support for the debug flag still on your radar?

**Comment by fhartwig** [comment]
> @fhartwig - would like to understand why your adapter is ignoring/overriding the test flag. In general, the expected behavior for bidders would be to discount impressions when 'test' is specified. If the aim is to avoid test requests to your bidder, I would think your adapter would just invalidate the auction rather than ignoring the explicit signal that this isn't a normal user.

@bretg I don't think there is a good reason for this behaviour, it's probably just something that was left over from the initial development and testing of the adapter. I will prepare a PR to remove this.
