### ISSUE TITLE
Where to place S2Sconfig file

### ISSUE THREAD

**Issue by RichardCR-10** [prebid/prebid-server#1353]
Hi all,
We are trying to get S2S prebid working inApp. While trying to set things up we ran into the issue where we need to setup an alias for one of the bidders in the so called S2Sconfig file (http://prebid.org/prebid-server/developers/default-request.html) However it is unclear to us where we need to put this file. Does anyone know if there is more information regarding this? Or simply knows the answer?

**Comment by SyntaxNode** [comment]
The configuration file for Prebid Server referred to by the "Config Options" sample of that doc is named `pbs.yaml` in either the same directory as the executable or in `/etc/config`. The file path you then specify for the default stored request itself can be anywhere you like.

You may alternatively use environment variables. This is what those look like from the sample:
```
PBS_DEFAULT_REQUEST_TYPE="file"
PBS_DEFAULT_REQUEST_FILE_NAME="/path/to/aliases.json"
PBS_DEFAULT_REQUEST_ALIAS_INFO="false"
```

**Comment by RichardCR-10** [comment]
Hi @SyntaxNode, thank you for the reply. Together with my colleague we looked at this and we feel this might not be possible as we're trying to run on an app and we're using the AppNexus hosted prebid server. Or are we misinterpreting your answer?

**Comment by SyntaxNode** [comment]
The Default Request document you linked to is a host specific feature. That's why I thought you were asking about hosting yourself. Sorry.

If you're using the Xandr hosted instances, then I think you're actually looking for the [Stored Request](http://prebid.org/prebid-server/developers/stored-requests.html) functionality. This is where you upload a request to Xandr's servers and use it as a template.

Xandr has two different types of hosting solutions, Prebid Server and Prebid Server Premium. The process for configuring a Stored Request is different for each. If you're using Prebid Server, login to https://prebid.adnxs.com/ with your account credentials and upload from there. If you're using Prebid Server Premium, you'll need to use our Xandr Monetize frontend.

If you are indeed looking for Stored Requests and have issues, please follow up either with your account manager or email us directly at prebid-server@xandr.com.

**Comment by RichardCR-10** [comment]
Thank you @SyntaxNode!
