### ISSUE TITLE
Support macros in bidder endpoints

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#1488]
## Description

Adhese requires that each publisher have their own endpoint. 

Currently endpoints are defined as URLs. For example:

PBS-Go:
```
v.SetDefault("adapters.rubicon.endpoint", "https://exapi-us-east.rubiconproject.com/a/api/exchange.json")
```
PBS-Java:
```
adapters:
   rubicon:
   enabled: false
   endpoint: https://exapi-us-east.rubiconproject.com/a/api/exchange.json
```
Adhese requires that the host name differ for each PBS account ID, along with other end point variations.

## Proposal

Rather than require a deploy of account-specific configuration, we propose that incoming request parameters can be used as macros to be resolved within the definition of the end point. e.g.

```
adapters:
   adhese:
     endpoint: https://ads-{{ext.prebid.bidders.adhese.acct}}.adhese.com/json/sl{{ext.prebid.bidders.adhese.location}}-{{ext.prebid.bidders.adhese.format}}
```
Then in Prebid.js:
```
pbjs.setConfig({s2sConfig: {
  ...
  extPrebid: {
    bidders: {
      adhese: {
        acct: "tmg",
        location:"pbs_test",
        format: "pbs_mr"
      }
    }
  }
});
```

The final results would be that the endpoint resolves to `https://ads-tmg.adhese.com/json/slpbs_test}-pbs_mr`

## Requirements

1. The macros must support sourcing values from `ext.prebid`. It would be even better if we could define any valid OpenRTB path. (e.g. site.ext.data.foo)
2. The endpoint macros should be resolved immediately before the URL is actually needed, and be based on that bidder's specific OpenRTB.
3. If they don't have first party data permissions, they shouldn't be allowed to access site.ext.data.foo
4. Any macro that doesn't resolve to an OpenRTB path should resolve to the empty string with a warning in the debug output.

**Comment by laurb9** [comment]
I am not sure if this should be supported for the vanity hostname part. It would cause pbs to have to open a connection for each pub, possibly starving the other bidders sharing the connection pool.

And because the host likely uses wildcard DNS for this, a simple DOS against a prebid-server is possible by sending requests with random acct value to make pbs close and reopen bidder connections until it runs out of sockets. Unless the pool is by IP, which still means perf degradation.

**Comment by bretg** [comment]
Interesting objection @laurb9 .

The other option is to define a bidder-specific account field in the Database. We've been dancing around this for a while.

1. define a new JSON field 'bidderConfig'  that can come back with the accounts query. Let this value grow with time -- e.g.

```
{
  "adhese": {
    "endpoint": "URL"
  },
  "brightroll": {
    "badv": ["a.com","b.com"],
    "bcat": []
  }
}
```

2. Update Prebid Server to support the endpoint override specifically.
3. Define a way to pass the bidder-config object to the adapters. Maybe merged into `ext.prebid.bidders.BIDDER`?

Any thoughts @SyntaxNode?

**Comment by SyntaxNode** [comment]
> Currently this cannot be supported.

This is supported in PBS-Go today. Adapters have full control over the URL construction and most of these adapters have implemented macros. This is a necessary feature because some bidders exclusively put their auction data in the URL as an HTTP GET request. As you've mentioned here, some bidders also include account ids or other publisher specific identifiers in their domain.

How do these adapters work today in PBS-Java?

> we propose that incoming request parameters can be used as macros to be resolved within the definition of the end point

This looks good in theory, but parsing these dynamic macros adds additional complexity to the code and additional computation time on the host. This approach is absolutely necessary for things such as dynamic targeting data that is controlled by the publisher, but Adapters already have their relevant information verified and parsed with the ability to construct URLs and use macros.

> I am not sure if this should be supported for the vanity hostname part. It would cause pbs to have to open a connection for each pub, possibly starving the other bidders sharing the connection pool.

Agreed. However, this functionality is already present and it's too late for us to "put the cat back in the bag". The fact is there are bidders which require custom domains and as a neutral platform I believe we should provide support. Perhaps we can more clearly explain to hosts which adapters are using dynamic domains, should the host decide the potential downsides aren't worth it and disable those adapters.

FWIW we are currently testing how the connection pools behave when under stressful situations. This work may very well turn into new features and new options to give hosts better control over how PBS-Go opens and maintains external connections. We added metrics on outgoing connections a few months ago to begin gathering data, if you'd like to take a look.

> The other option is to define a bidder-specific account field in the Database

The recent implementation of accounts in PBS-Go (thanks @laurb9) is an abstraction on top the storage format. It currently works with the file system and I expect this to be expanded to database and http backends as time goes on. So to be a bit pedantic here, I'll consider an account field in the database to be an account specific field, however the information is sourced. 

> Any thoughts @SyntaxNode?

It seems interesting. I'm curious if the current method we have of using stored requests and stored impressions doesn't provide enough flexibility. Have you heard of publishers unhappy with the current approach?

> Define a way to pass the bidder-config object to the adapters. Maybe merged into ext.prebid.bidders.BIDDER?

Encoding the account specific bidder data into the OpenRTB request sounds a bit expensive to me in terms of extra JSON serialization, but it might be nice if we want to act as overrides for what the publisher includes in the request. Otherwise, I'd be more included to pass an object to the adatpers.

**Comment by bretg** [comment]
Closing this issue. 

Bidders that need pub-specific endpoints are already handling this themselves, and that's how we'll leave it for now.

If we run into issues with a bidder having vanity URLs, the immediate solution for the host company will be to remove the bidder entirely.  In the meantime, we could consider working towards account-specific bidder config coming from the database. But that's a feature for another time and issue.
