### ISSUE TITLE
Invalid Kubient, Smart Ad Server, Applogy, NinthDecimal, Inmobi Support Emails

### ISSUE THREAD

**Issue by SyntaxNode** [prebid/prebid-server#1594]
Does anyone have other ways to contact these companies?

Their email addresses from the bidder info files of support@kubient.com, support@smartadserver.com, work@applogy.com, abudig@ninthdecimal.com, and prebid-support@inmobi.com respond with undeliverable errors.

**Undeliverable Emails**
- [x] Kubient (fixed, thanks @mapcuk)
- [ ] Smart Ad Server
- [ ] Applogy
- [ ] NinthDecimal
- [x] Inmobi

**Non-Group Emails**
- [x] AdPrime
- [x] DeepIntent (fixed, thanks @sourabhg)
- [x] DMX (fixed, thanks @stevealliance)

**Comment by bretg** [comment]
- Kubient - @mapcuk
- SmartAdServer - @tadam75 
- Applogy - @IncSW 
- Ninthdecimal - @trchandraprakash 

I have contact info for inmobi and am working with them to resolve.

To this list I'm going to add the adapters for which we need group emails rather than individual emails. The individuals for which we have email addresses are not responding. Which is why we prefer group addresses.

- AdPrime @Adprime 
- DeepIntent @sourabhg 
- DMX @steve-a-districtm , @stevealliance

**Comment by SyntaxNode** [comment]
@bretg Do you have updated support email addresses for the Smart Ad Server, Applogy, and/or Ninth Decimal?

**Comment by bretg** [comment]
- I slacked SmartAdServer since they're Prebid.org members.
- Used inmarket.com's web contact form in an attempt to get a new maintainer. My success rate with web contact forms is 0-for-many.
- can't find convincing reference that applogy is even a company anymore. @IncSW

**Comment by SyntaxNode** [comment]
Closing in favor of https://github.com/prebid/prebid-server/issues/2626.
