### ISSUE TITLE
Client IP in request body

### ISSUE THREAD

**Issue by gchicoye** [prebid/prebid-server#1662]
Hi everybody,

I struggle getting Device.Ip populated in Bid Request sent to SSPs
Is there something I'm missing into my Prebid-Server parameters? I've tried many things around lmt, gdpr, but without success...

Thanks a lot for your help!

```
{
   "id":"test",
   "imp":[
      {
         "id":"header_ad",
         "banner":{
            "format":[
               {
                  "w":300,
                  "h":250
               }
            ],
            "w":300,
            "h":250
         },
         "tagid":"/21805930009/test",
         "secure":1,
         "ext":{
            "appnexus":{
               "placement_id":16074818
            }
         }
      }
   ],
   "site":{
      "domain":"...",
      "page":"..."
      "ext":{
         "amp":1
      }
   },
   "device":{
      "ua":"PostmanRuntime/7.26.8"
   },
   "user":{
      "ext":{
         "consent":"..."
      }
   },
   .... 
}
```

**Comment by SyntaxNode** [comment]
Do you either:
1. Expect Prebid Server to populate the IP address (since I don't see it in your example above), or
2. Are including the IP address in the request and Prebid Server is removing it?

The latter could be caused by a privacy policy, as you've been exploring. PBS also filters out private network and multicast IP addresses, as those are of no value to third parties. If you're testing from a 192.168.x.x address, you might be encountering this situation.

Happy to help if you could please provide a bit more info.

**Comment by gchicoye** [comment]
Thanks a lot for your prompt respond,
Please find my answer below
1. Expect Prebid Server to populate the IP address (since I don't see it in your example above) => Yes, indeed - I'm running some "live tests" on real life websites, on both POST /openrtb2/auction and GET /openrtb2/amp
You can find an exemple (with debug included) here https://www.phonandroid.com/iphone-12-le-chargeur-et-les-ecouteurs-ne-seront-livres-avec-le-telephone-par-souci-decologie.html/amp
2. IPs are by nature included into the bid request (nothing is hidden) as header details, it looks like Prebid is removing it...

I've done many tests without success, for instance
```
gdpr:
  usersync_if_ambiguous: true
lmt:
  enforce: false
```

Please let me know if you need more informations, thanks again!!!

**Comment by SyntaxNode** [comment]
Thank you for the example. That was very useful in understanding your situation. To recap:
- You are running your own PBS instance and have a test page using AMP.
- AMP relies on stored requests and cannot have the client js (AMP) include the ip address.
- I verified using a simple auction on your server that IP address is not being removed by PBS when no privacy policy applies (no LMT, CCPA, COPPA, or GDPR).

PBS will populate the IP address of an OpenRTB request if it's not already defined in the request. This works across all amp, auction, and video endpoints. The code looks at the `True-Client-IP`, `X-Forwarded-For`, and `X-Real-IP` headers before using the ip address directly received by the server. We have CI tests to ensure this works and I manually tested on my machine just now.

I can see two questions to guide us forward:
1. What version of PBS are you using? The ip address resolution feature was added about 7 months ago.
2. What is sitting between your internet connection and your PBS instance?

Assuming you're using the current version, the issue is likely a loss of information between your edge servers and your instance. If the edge servers aren't populating any of the forwarding headers I mention in this reply, then your server is likely getting an internal network address and filtering it out.

**Comment by gchicoye** [comment]
Thanks to your response, I've found the fix :)
As I'm running a quite recent version of PBS, I had a look at the Nginx proxy configuration which is ahead of our PBS instance.
I've added the following lines to my proxy_pass configuration to make sure correct headers we're sent, and it fixed the issue. 
```

proxy_set_header X-Real-Ip $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
proxy_set_header REMOTE_ADDR $remote_addr; 
````
Thanks again for your help!
