### ISSUE TITLE
Document current status of demand adapters

### ISSUE THREAD

**Issue by nhedley** [prebid/prebid-server#173]
All of the demand adapters support different media-types (banner, video, native) as well as supply types (web, mobile). This should definitely be tracked somewhere so that it is easy for developers to know without digging through the code what an adapter supports.

@dbemiller is thinking to do this through APIs.

Might need to add a GET /bidders endpoint which returns something simpler, like:

[
  "appnexus",
  "rubicon",
  ...
]
And maybe a /bidders/media-types which returns something like:

{
  "appnexus": ["banner", "video"],
  "index": ["banner"]
}
Basic motivation is: docs fall out of date all the time. Since we're running a server anyway, we should be able to generate these things from the code, so they're guaranteed to be up to date.

It'll also help with the fact that different companies might deploy different versions of PBS... so the features might be different depending on whose deploy you're using.

**Comment by dbemiller** [comment]
This has been on my TODO list ever since it was filed... gonna start it now.

My plan is to add all this stuff to the `info.yaml` file, and then make the core auction logic reject "invalid" bid types so that adapters have incentive to maintain them.

The API endpoints will respond using data from the `info.yaml` files. In the more distant future, we can use these to generate human-readable docs that stay up to date with the code.
