### ISSUE TITLE
Incorrect user agents seen by adapter

### ISSUE THREAD

**Issue by patmmccann** [prebid/prebid-server#1747]
We are currently working on a ticket to pass user agent as a param on the call to pbs-go because @sourabhg and co are reporting they are seeing a static user agent 'Go-http-client/1.1' 

We would prefer adapters saw the actual user agent of the machine making the request to PBS when this parameter is missing or empty from the endpoint parameters but is populated in the http headers

**Comment by SyntaxNode** [comment]
> pass user agent as a param on the call to pbs-go

Could you please clarify the change you're looking to make? Is this isolated to a specific adapter or is this a feature request for PBS-Core?

The request to bidding servers is indeed originating from Prebid Server's Go http stack, so a default user agent of `Go-http-client/1.1` sounds right to me.

The user's user agent is available from within the OpenRTB bid request in `request.device.ua`. If this value is already populated by client systems, such as PrebidJS or the Prebid SDKs, it will be passed as-is to the adapter. If this value is empty, Prebid Server will populate it from the request header. Some bidding servers look for the user agent in the headers instead of in OpenRTB bid request body. That's fine and can be accommodated today with the adapter adding the value to the outgoing request headers. A few examples of adapters doing this are acutityads, adform, and telaria.

**Comment by bretg** [comment]
FWIW - PBS-Java doesn't set the HTTP User-Agent header on outbound requests. Like PBS-Go, UA is in `request.device.ua`

**Comment by patmmccann** [comment]
Thanks for clarifications, closing because it seems like we had incomplete information from our adapter partner.
