### ISSUE TITLE
Do not call a bidder without GDPR consent

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#1781]
Is there some configuration available in the openrtb request set to prebid-server to inform it that it should not send the bid requests to ssps that did not received consent ? So far, when a ssp does not have its consents the buyer uid is not sent to him, that's the default behavior which I a fine with, but would there be some flag to had in order to avoid the request to be sent at all ?

Thanks

**Comment by hhhjort** [comment]
There is nothing currently set up to accomplish this. I am not sure this is specifically a GDPR issue, but a buyer uid issue. Are you looking to specifically not send a request if the buyer uid is not provided due to a GDPR consent issue, but still send a request if the buyer uid is absent for any other reason? Or simply not send requests when the buyeruid is missing, for whatever reason?

Assuming that you want to block bidding on no buyer uid, there are two places that it could potentially be added. One is in the adapter itself, if a bidder knows that they do not want to bid when buyer uid is not set, they can simply not generate any bid requests to be sent. The other would be within the main loop itself, which would need some configuration around it to determine when a request should be blocked or not.

Could you flesh out what you are trying to accomplish exactly, so we can narrow down the requirements/specs for what you need?

**Comment by matthieularere-msq** [comment]
It's more a publisher concern issue. Some of our publishers wants to be sure not to call the ssps which received no consent as their legal team asks them not to. 
So indeed I am specifically looking not to send the request if the buyer uid is not priveded due to a GDPR consent issue, but still send a request if the buyer uid is absent for any other reason.

However, you anticipated one request that I will have later: not sending the request to some specific ssps when they have no buyer uid for whatever reason. I know some of the ssps I am working with and have a low cookie matching rate are going to ask soon.

**Comment by hhhjort** [comment]
Currently there is no functionality to do this. I imagine that it would have to be an account level setting to check for vendor consent and block the request if consent is missing, as not all publishers may not want to block that. One complication is that TCF2 defines both explicit vendor consent, and legitimate interest consent. That is, a user may not consent to vendor A, but may accept that vendor A does have a legitimate interest in seeing the user's PI. A solution would have to consider both of these as potential "consent"s. I don't see any particular issue adding something like this to PBS, but no one that I know of is currently working on a feature like this. Please feel free to submit a more formal spec for this feature if it is something you wish to work on. Or submit the spec in hopes someone else picks it up before too long. And feel free to continue the conversation here for help and advice in generating a more formal spec.

**Comment by hhhjort** [comment]
Reviewing further, PBS Go does not currently check Purpose 2 (ad auctions) consent before sending out a bid request. We will scrub PI if consent is missing, but not block completely. This is now on our to-do list to block bid requests on Purpose 2 (configurable on/off). Unless you want to send bids when the user consents to a bidder, but does not consent to Purpose 2, this should cover your use case of blocking bid requests to bidders without consent.

**Comment by bsardo** [comment]
Implemented in PR #1851.
