### ISSUE TITLE
version sync with pkg.go.dev (PBS As A Library)

### ISSUE THREAD

**Issue by alkmc** [prebid/prebid-server#1845]
If you look at https://pkg.go.dev/github.com/prebid/prebid-server?tab=versions,
you can see that Github repo release tags do not match with **_pkg.go.dev_** version. 

The reason for what is that Go applications are expected to be versioned with a starting 'v' in the tag,
 for example _**v0.159.0**_ and not **_0.159.0_**. 

 Go.mod uses versioning analogous to _**pkg.go.dev**_ example:
 _github.com/prebid/prebid-server v0.0.0-20210510193605-585283f30b66_
could be clearer as:
 _github.com/prebid/prebid-server v0.159.0_
 
 Would it be a problem for the next version to be tagged as v0.160.0?

**Comment by alkmc** [comment]
Yes, I do with Go version 1.16.

**Comment by SyntaxNode** [comment]
> Yes, I do with Go version 1.16.

Interesting. I'm curious if you would be able to tell us a bit more how you use PBS as a module? It's not a use case we've envisioned. We've been historically focused on distributing a binary and haven't been given much concern to adherence to Go's versioning expectations for PBS as a module.

I'd be happy to make it easier to import PBS through Go modules. I don't expect it to start as soon as version 0.160.0. Let's use this thread to discuss our options. There are some downstream effects we need to consider.

If we change the tag from 00.00.00 to v00.00.00 moving forward:
1) Release Names: The path of least resistance would be name the releases "v00.00.00". We haven't been consistence with release names anyhow, so I don't see this as a problem. Am I correct in assuming the Go versioning logic doesn't care about GitHub release names? We could remove the "v" in the GitHub Action if we want to keep with the "00.00.00" pattern. That should be simple.

2) DockerHub Images: I'm hesitant to begin adding a "v" to the tags and image names. I'm concerned it could break someone's scripts. I imagine we could remove the "v" in the Docker build script without much trouble.

3) Downstream Build Pipelines: Similar to the change in DockerHub tags and image names, I'm worried what others may have built on the assumption of our current "00.00.00" tag scheme. I'd like to provide advance notice of our intent to make the change to give folks time to update their systems as necessary.

4) Embedded PBS Version: We don't do this today, but there are issues open for us to include the version number in PBS for the version endpoint and adding the version to request and response headers. Should these values include the 'v"?

Another option be to emit 2 tags, one like we have now and one with the "v". Would this make Go happy? The intent with this option is to keep the build process largely the same and add a new tag for Go, but then having 2 similar tags per release will likely introduce new problems of its own.

I wonder if this might be a good time to also consider an increment to 1.0. The original idea was to wait until there was a versioned Prebid.org API to be shared between PBS-Go and PBS-Java, but that hasn't happened. We will be removing the /auction endpoint and original PBS object model soon, so that might be a good time to move to a 1.xx.xx.

**Comment by SyntaxNode** [comment]
Another thought: How much stability do you expect from PBS as a module?

I currently consider all packages in this project existing solely for the benefit of the PBS compiled binary. In refactoring, we will often rename packages and alter exported types. I'm concerned promising stability in those areas would greatly hinder our ability to move the project forward.

Perhaps there are certain packages you care about which we might consider keeping more stable?

**Comment by alkmc** [comment]
> > Yes, I do with Go version 1.16.
> 
> Interesting. I'm curious if you would be able to tell us a bit more how you use PBS as a module?

We mainly use prebid.js on the client side, but for some reasons the frontend team didn't implement some functionality there, so we used prebid-server as the backend module to implement it.

**Comment by alkmc** [comment]
The last thing I want when asking for this change is complicating the build process for someone else or breaking the script.

It is about:
https://golang.org/doc/modules/version-numbers

As you can see it is possible to create tags for Go projects starting with v in tag for whose who import it inside go.mod:
https://github.com/docker/cli/releases
And release it without v in version:
https://docs.docker.com/engine/release-notes/

**Comment by alkmc** [comment]
> 4. Embedded PBS Version: We don't do this today, but there are issues open for us to include the version number in PBS for the version endpoint and adding the version to request and response headers. Should these values include the 'v"?

I don't think 'v' is necessary there, but it is open for discussion.

**Comment by alkmc** [comment]
> Another option be to emit 2 tags, one like we have now and one with the "v". Would this make Go happy? The intent with this option is to keep the build process largely the same and add a new tag for Go, but then having 2 similar tags per release will likely introduce new problems of its own.

I believe this is too much of a complication.

**Comment by alkmc** [comment]
> I wonder if this might be a good time to also consider an increment to 1.0. The original idea was to wait until there was a versioned Prebid.org API to be shared between PBS-Go and PBS-Java, but that hasn't happened. We will be removing the /auction endpoint and original PBS object model soon, so that might be a good time to move to a 1.xx.xx.

take your time, it's up to you to decide on v1

**Comment by alkmc** [comment]
> Another thought: How much stability do you expect from PBS as a module?
> 
> I currently consider all packages in this project existing solely for the benefit of the PBS compiled binary. In refactoring, we will often rename packages and alter exported types. I'm concerned promising stability in those areas would greatly hinder our ability to move the project forward.
> 
> Perhaps there are certain packages you care about which we might consider keeping more stable?

It would be enough for me if:
_go get https://github.com/prebid/prebid-server_
was downloading the latest tagged version, not the version with the most recent change.
That would happen if version were tagged with v.

**Comment by SyntaxNode** [comment]
Thank you for the responses @alkmc. Based on feedback, here's the proposal:

- Starting with version 0.161.0, write the tag as "v0.161.0" for proper compliance with Go's versioning expectations.
- Remove the "v" from the version tag for all other uses: release name, docker image tag and name, version embedded in PBS.
- Make it clear through documentation that PBS packages are not intended to be used as a standalone module. You're of course welcome to do so, but we make no stability promises.

**Comment by bretg** [comment]
> We mainly use prebid.js on the client side, but for some reasons the frontend team didn't implement some functionality there, so we used prebid-server as the backend module to implement it.

@alkmc - why aren't you running PBS as a standalone server? Are you integrating the functionality into an existing Go server you already run?

**Comment by alkmc** [comment]
> @alkmc - why aren't you running PBS as a standalone server? Are you integrating the functionality into an existing Go server you already run?

Yes, we have added some PBS functionality to the existing Go proxy service.

**Comment by alkmc** [comment]
> Thank you for the responses @alkmc. Based on feedback, here's the proposal:
> 
> * Starting with version 0.161.0, write the tag as "v0.161.0" for proper compliance with Go's versioning expectations.
> * Remove the "v" from the version tag for all other uses: release name, docker image tag and name, version embedded in PBS.
> * Make it clear through documentation that PBS packages are not intended to be used as a standalone module. You're of course welcome to do so, but we make no stability promises.

I can see that tag was released as 0.161.0, not v0.161.0, was there any problem with proposed change?

**Comment by SyntaxNode** [comment]
> @SyntaxNode
> I can see that tag was released as 0.161.0, not v0.161.0, was there any problem with proposed change?

No problem. We just didn't have time this week to implement the build process update. There was unexpected craziness for us this week. Expect to see this implemented next week for v0.162.0.

**Comment by SyntaxNode** [comment]
Version 0.162.0 has released with the new "v" tag. We'll continue with this format moving forward.
