### ISSUE TITLE
adapter with vendor id asking only for purpose 1

### ISSUE THREAD

**Issue by matthieularere-msq** [prebid/prebid-server#1929]
Hi,

I am trying to create an adapter for a vendor which only ask for consent purpose 1 in vendor-list.json : 
`"purposes":[1],"legIntPurposes":[],"flexiblePurposes":[],"specialPurposes":[],"features":[],"specialFeatures":[]`

However, it seems that this is not enough for function checkPurpose to return true. Is this the expected behavior? In my gdpr consent string, all purposes were consented and my vendor id is consented too, why should it be rejected ? 
For instance, vendor id is 285 and consent string is : 
`CPIgxX6PIgxX6AKAfAENBgCsAP_AAH_AAAqIIAtf_X__bX9j-_59f_t0eY1P9_r_v-Qzjhfdt-8N2L_W_L0X42E7NF3apq4KuR4Eu3LBIQNlHOHUTUmw6okVrTPsak2Mr7NKJ7LEmnMZe2dYGHtfn91TuZKY7_78_9fz3z-v_v___9f3r-3_3__59X---_e_V399zLv9_____9nN_gc-ASYal8AFmJY4Ek0aVQogQhWEh0AoAKKAYWiawgIGBTsrAI9QQMAEBqAjAiBBiCjFgEAAAAASERASAHggEQBEAgABACpAQgAIkAQWAEgYBAAKAaFgBFAEIEhBkcFRymBARItFBPJWAJRd7GGEIZRYAUCj-ioAAAAA.f_gAAAAAAAAA`

Thanks for your help,
Matthieu

**Comment by bsardo** [comment]
Hi @matthieularere-msq,

If you could share some more information, that would be great.
- What version of PBS-Go are you running?
- Just to confirm, the vendor in question is vendor ID 285 and you’re creating a new bidder for that vendor right?
- Are you able to share the GDPR portion of your config file?

Thanks

**Comment by matthieularere-msq** [comment]
Hi @bsardo 

- I am not on a specific version for this dev, I am on the master branch cloned yesterday
- I am indeed trying to create a new bidder for this vendor
- You mean static/bidder-info/{bidder}.yaml file ? If so, all I have about gdpr is this :
`gvlVendorID: 32`
Is there anything more to add to the file or to some other file ?

Thanks

**Comment by bsardo** [comment]
I was curious if you had created a `pbs.yaml` or a `pbs.json` at the root with GDPR configuration defined that would effectively override the default GDPR configurations defined in `config/config.go` function `SetupViper`. If you don't have this file, did you modify any of the defaults directly in that file by tweaking some of the `SetDefault` calls?

Also in order to start up PBS you need to specify a value for `gdpr.default_value`. What did you set this to?

And are you able to share the entire sample request you're using so I can try to reproduce the issue?

**Comment by matthieularere-msq** [comment]
I do have a pbs.yaml indeed, I haven't thought about it. Here is its gdpr part : 
```
gdpr:
        host_vendor_id: 791
        timeouts_ms.init_vendorlist_fetches: 1000
        timeouts_ms.active_vendorlist_fetch: 1000
        default_value: 1
```

**Comment by matthieularere-msq** [comment]
I forgot about the sample request you asked for :
`{"device":{"ip":"__IP__","ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36","language":"fr","geo":{"country":"FRA","ipservice":3}},"ext":{"prebid":{"targeting":{"pricegranularity":{}},"debug":true},"tagId":"db6419bd-b9a2-4c8e-8a48-879319608167"},"id":"4992a6e2-78e2-4bbc-b1c3-7af5dbdf5179","imp":[{"video":{"mimes":["video/mp4"],"minduration":null,"maxduration":null,"protocols":null,"startdelay":null,"placement":null,"skip":null,"skipafter":null,"minbitrate":null,"maxbitrate":null,"delivery":null,"playbackmethod":null,"api":null,"linearity":null,"w":null,"h":null,"boxingallower":null,"playersize":[[640,480]]},"ext":{"context":{"pubstack":{"adUnitName":"atf_desktop_rg_native"}},"freewheel":{"zoneId":594753},"appnexus":{"placementId":15372872}},"id":"fC20sy0vlsPxD8sZSBzC1j70CcfMXU","secure":1,"tagid":"msq_tag_200125_video"}],"regs":{"ext":{"gdpr":1}},"site":{"page":"https://debug.mediasquare.fr/debug/prebid/msq_video.html?pbjs_debug=true"},"tmax":1300,"user":{"ext":{"consent":"CPIgxX6PIgxX6AKAfAENBgCsAP_AAH_AAAqIIAtf_X__bX9j-_59f_t0eY1P9_r_v-Qzjhfdt-8N2L_W_L0X42E7NF3apq4KuR4Eu3LBIQNlHOHUTUmw6okVrTPsak2Mr7NKJ7LEmnMZe2dYGHtfn91TuZKY7_78_9fz3z-v_v___9f3r-3_3__59X---_e_V399zLv9_____9nN_gc-ASYal8AFmJY4Ek0aVQogQhWEh0AoAKKAYWiawgIGBTsrAI9QQMAEBqAjAiBBiCjFgEAAAAASERASAHggEQBEAgABACpAQgAIkAQWAEgYBAAKAaFgBFAEIEhBkcFRymBARItFBPJWAJRd7GGEIZRYAUCj-ioAAAAA.f_gAAAAAAAAA"}}}`
But I doubt you can do much with it considering the bidder which fail gdpr is the one I am working on.
Though what you can do is to change appnexus' vendor id to 285, it will have the same issue, I tested that too.

**Comment by bsardo** [comment]
Thanks for the info.

I assume you're hitting the `/openrtb2/auction` endpoint with this request. In that case, `checkPurpose` is only called in two places:
1) in `impl.go` function `allowActivities` to determine if the bid request is allowed (purpose 2 is examined)
2) in `impl.go` function `allowActivites` to determine if the user data should be passed in the bid request (purposes 2-10 are examined)
In each of these cases, we do not consider purpose 1 so `checkPurpose` correctly returns false in both cases.

Given that the vendor only asks for purpose 1 in the vendor list, the behavior you are observing is correct; the user consents but the vendor has not declared purposes 2-10 so the purpose check fails. Some of the ways this could be addressed are:
1. by the vendor allowing other purposes
2. by the host listing the vendor as a vendor exception in the PBS GDPR config for the applicable purposes
3. by the host listing the purpose as not enforcing vendors in the PBS GDPR config for the applicable purposes
It should be noted that options 2 and 3 will not consider some or all of the consent string so that may not be what you want.

If you're hitting the `/cookie_sync` endpoint, `checkPurpose` is called on purpose 1 to determine if the sync is allowed and in that case it returns true as expected.

I hope that helps. Let me know if you need any more assistance.

**Comment by matthieularere-msq** [comment]
Indeed I am hitting `/openrtb2/auction`.
You mention that one solution would be : 
"by the host listing the vendor as a vendor exception in the PBS GDPR config for the applicable purposes"
Could you point me to the documentation about how to do so ? I haven't seen something that would look like such an option in config.go.

Thanks

**Comment by bsardo** [comment]
Hi @matthieularere-msq,

The documentation hasn't been updated yet but you'll notice the following fields are set to `[]openrtb_ext.BidderName{}` in `config/config.go`:
```
gdpr.tcf2.purpose1.vendor_exceptions
gdpr.tcf2.purpose2.vendor_exceptions
gdpr.tcf2.purpose3.vendor_exceptions
gdpr.tcf2.purpose4.vendor_exceptions
gdpr.tcf2.purpose5.vendor_exceptions
gdpr.tcf2.purpose6.vendor_exceptions
gdpr.tcf2.purpose7.vendor_exceptions
gdpr.tcf2.purpose8.vendor_exceptions
gdpr.tcf2.purpose9.vendor_exceptions
gdpr.tcf2.purpose10.vendor_exceptions
gdpr.tcf2.special_purpose1.vendor_exceptions
```

You can include your bidder name in these `vendor_exceptions` in your `pbs.yaml` file so checks for a given purpose will return true assuming a valid consent string was provided and there wasn't a publisher restriction specified in it.

**Comment by bretg** [comment]
What's your use case @matthieularere-msq ?

When we defined [PBS GDPR enforcement](https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#heading=h.8cgpj780kmcq), it was assumed that every bidder would declare Purpose 2. These are auctions for ads after all... if a bid adapter isn't bidding on ads, then it shouldn't be a bid adapter -- it's some other kind of thing, e.g. viewability. PBJS just went through the effort of pushing 2 adapters from bid adapters to real-time-data modules because they didn't return ads.

So if the code adheres to the written algorithm in the doc, it will not allow P2 for a vendor that doesn't declare a basis for it. The workaround, as suggested above, it that a host company can turn off P2 enforcement off for a given adapter.

**Comment by matthieularere-msq** [comment]
@bretg Well the bidder I am trying to create an adapter for is a SSP, though they just ask consent for purpose 1. Truth is I can't say why they don't ask for purpose 2 too but I'll check with them. 

I'll test the solution proposed and will confirm if it solves my issue.

**Comment by matthieularere-msq** [comment]
@bretg I got the answer from the vendor about why they only asks for purpose one: they consider themself as processor and not controller. I am no specialist of gdpr so I can't say if that's a good explanation, but that's the one they gave me.

**Comment by bretg** [comment]
> they consider themself as processor and not controller.

I'm not a lawyer, but in the scope of Purpose 2, this isn't a strong enough reason for Prebid to change positions.  https://iabeurope.eu/iab-europe-transparency-consent-framework-policies/#Purpose_2__Select_basic_ads_ ... consenting to purpose 2 means:

"Ads can be shown to you based on the content you’re viewing, the app you’re using, your approximate location, or your device type."

The Prebid default is to interpret a user **not consenting** to P2 to be the opposite... that ads cannot be shown.
But we're aware that lawyers have many interpretations of these rules, so built in flexibility. In this case, a host company config can give a given vendor a pass by setting `gdpr.tcf2.purpose2.vendor_exceptions: bidderA`

You can document that host companies have to grant this exception or the adapter won't bid in GDPR territories.

**Comment by matthieularere-msq** [comment]
I confirm it works with `gdpr.tcf2.purpose2.vendor_exceptions: bidderA` in pbs.yaml
Thanks
