### ISSUE TITLE
New Rhythmone error on S2S

### ISSUE THREAD

**Issue by spormeon** [prebid/prebid-server#1937]
On P5.1.0 this error has started to appear, is this newly introduced or is something up? If its purely there for "info" that there is "no bid", don't really see the point of it?

![124907964-ae028080-dfe0-11eb-847a-8ee7de1e9dd7](https://user-images.githubusercontent.com/8503167/126825337-766afb6c-bebf-4de7-a698-fc70fbe40a76.png)

**Comment by mansinahar** [comment]
@spormeon This error indicates that Rhythmone is bidding with a price less than or equal to 0. I am not exactly sure which version is `P5.1.0` referring to but this isn't new.

**Comment by bretg** [comment]
Doubt this has anything to do with PBJS 5.1. More likely that rhythmone started returning 0-value bids.

That error message comes from bidder_validate_bids.go, but was recently changed - about 2 weeks ago. It should now read either:

- "Bid \"%s\" does not contain a positive (or zero if there is a deal) 'price'", 
- "Bid \"%s\" does not contain positive 'price' which is required since there is no deal set for this bid", bid.bid.ID)

As far as I can tell, the message will only appear if there's actually a bid.

**Comment by mansinahar** [comment]
@spormeon Does the explanation Bret gave above make sense? If so, can this be closed?

**Comment by spormeon** [comment]
it makes sense but i not sure why the error is there/ shows, i dont see the point in it, if rhythmone "does not contain a positive price", why not flag all the others as well that made no bid.  I cant see why it would be useful to know " no price" in effect

**Comment by mansinahar** [comment]
@spormeon As Bret mentioned above, this is likely happening because Rhythmone is sending back $0 bids. Prebid Server used to consider $0 bids as invalid bids but in a recent change it _allows_ $0 bids in case of _deals_. I'd suggest enabling debug on your request and inspecting if the bid price is negative or $0 and if you expect $0 bids for a deal then we recommend you coordinate with your Prebid Server host and ask them to update to the latest version to allow that behavior.

However, If the bidder is sending bids that have a negative price or a $0 price without a deal present then that is considered an invalid bid which indicates something is wrong on the bidder side and this error helps the publisher know that and possibly communicate that with the bidder. Invalid bids are different from no bids. No bids don't necessarily indicate an erroneous behavior. The bidder can chose to not bid on a request for various reasons.

**Comment by bretg** [comment]
Opened #1973 to track cleaning the error log here -- this warning should only appear in debug mode.
