### ISSUE TITLE
Prebid OpenX amp Setup Problem

### ISSUE THREAD

**Issue by snezhko13** [prebid/prebid-server#1939]
Hi!
I have difficulties with OpenX AMP setup via Prebid.js. When I add OpenX it breaks the whole AMP Prebid.js. Has anyone encountered a similar problem?

Perhaps someone can share a screenshot of their OpenX AMP setup?I attached screenshot with my setup.
![image](https://user-images.githubusercontent.com/43814854/127129328-a644becc-9b73-42a0-a95f-5df331fecbba.png)
![image](https://user-images.githubusercontent.com/43814854/127129347-8b313c14-b17c-4add-899d-543ac9e2056a.png)

**Comment by mansinahar** [comment]
@snezhko13 Should this be a question for https://github.com/prebid/Prebid.js ?

**Comment by bretg** [comment]
Going to need more details @snezhko13 .  It's unclear why you mention Prebid.js, since AMP isn't a thing for them.

What is your actual problem? Here's my guess: you have your own Prebid Server set up with AMP stored requests. You're trying to update that stored request to include openx and the Prebid Server request fails. (am assuming your mention of Prebid.js is a typo)

If this is the correct problem, several questions:
- Did you notice that the "unit" parameter for OpenX is supposed to be a string and not an int? That could cause a problem.
- What version of PBS are you running (Go? Java? what version?)
- Do you have the openx bid adapter enabled?
- Have you checked the debug trace? https://docs.prebid.org/faq/prebid-server-faq.html#how-can-i-debug-prebid-server-requests

**Comment by bretg** [comment]
@snezhko13 - please see questions above.

**Comment by bretg** [comment]
@snezhko13 - we're going to close out this issue assuming that the OpenX "unit" parameter datatype was your underlying problem. Please re-open if you have additional details.
