### ISSUE TITLE
Unspecified query params in bidder endpoint

### ISSUE THREAD

**Issue by nllerandi3lift** [prebid/prebid-server#1960]
I would like to replace the [supplier_id in Triplelift's endpoint](https://github.com/prebid/prebid-server/blob/7a9bc316a28078c3c5749d717bfb112935ce59fd/config/config.go#L966) with 'GET_FROM_TRIPLELIFT' (or similar), as long as this change doesn't propagate to any host company that's successfully running our adapter today. We are making an effort to separate out unique supply sources and no longer want every supplier using the same id.

Just looking for some guidance if that would be an acceptable way to handle this request. 

Thanks

**Comment by SyntaxNode** [comment]
Many hosts running Prebid Server use the bidder's default endpoint. Would changing the supplier_id from it's current default to something like "GET_FROM_TRIPLELIFT" cause your server to reject the traffic? If not, then I don't see an issue with using the placeholder and hoping host companies will reach out to you to configure their own ids.

Otherwise, this is a tricky situation with no perfect solution. This would indeed propagate to host companies successfully running your adapter today. I think the best you can do in this case is to reach out to the host companies and ask they work with you to obtain a supplier_id and configure a url override.

Since this is an open source project without any kind of "dial home" functionality, we have no way of knowing who hosts Prebid Server. We do maintain and encourage host companies to identify themselves to us (Prebid.org), but few do. We can help you by sending a message to those hosts asking them to contact you and I can offer to add a note in the release notes.

In the end, you may choose to disable the Triplelift adapter by default and provide instructions in [your bidder doc](https://github.com/prebid/prebid.github.io/blob/master/dev-docs/bidders/triplelift.md) for how to activate it. You may have to cut off host companies who are unresponsive, but I hope most would recognize the Triplelift adapter being disabled by default and checking the docs and release notes to figure out how to solve it.

**Comment by nllerandi3lift** [comment]
Hi Scott. Thanks. 

> Would changing the supplier_id from it's current default to something like "GET_FROM_TRIPLELIFT" cause your server to reject the traffic?

Yes - this would reject traffic. I suppose then what's best is to leave the current id, since this has been acting as the catchall anyway, then reach out to companies individually to see if they can change within their own forked versions. 

> We can help you by sending a message to those hosts asking them to contact you and I can offer to add a note in the release notes.

This is good to know that it's an option, but I'll reach out to a few hosts on my own and get a few more of these off the ground before going this route.  

Thanks for the info.

**Comment by nllerandi3lift** [comment]
@SyntaxNode Would it be acceptable to place a README within our adapter directory?
https://github.com/nllerandi3lift/prebid-server/tree/master/adapters/triplelift
