### ISSUE TITLE
viewdeosDX server-side adapter not working

### ISSUE THREAD

**Issue by spormeon** [prebid/prebid-server#1980]
Hi

I cant find this info anywhere, I have a bidder that is saying in the docs they are a prebid server bidder and they have test params but when used they crash prebid server out, with a error of "are these an alias",  I don't know, the docs don't say they are.  there is no way to find out?

**Comment by bretg** [comment]
@spormeon - which bidder? The definitive list of bidders is https://docs.prebid.org/dev-docs/pbs-bidders.html

However, not every Prebid Server host company enables all bidders. e.g. Magnite has only enabled the following bidders -- https://prebid-server.rubiconproject.com/info/bidders?enabledOnly=true

It may be that your Prebid Server hasn't enabled this bidder, or perhaps the bidder's docs are incorrect.

**Comment by spormeon** [comment]
its viewdeos,  i got no clue if their an alias of something else though.

**Comment by bretg** [comment]
Hmm. viewdeos is a snowflake. For Prebid.js they have their own bid adapter, but for Prebid Server they're an alias of adtelligent. I updated the [viewdeosDX PBS bidder page](https://docs.prebid.org/dev-docs/pbs-bidders.html#viewdeosDX) with this note :

"Note that for Prebid Server, viewdeosDX is an alias of the Adtelligent server-side bid adapter. It has its own Prebid.js adapter."

I've added an agenda item to this Friday's PBS meeting to discuss a better long term solution.

**Comment by bretg** [comment]
@spormeon - we discussed in the committee meeting today.

We think the main issue here is that `viewdeos` is the correct alias for the server-side adapter rather than 'viewdeosDX'.

The general idea is that aliases should not be something publishers need to think about... they should look like a standalone bidder. I'm going to reach out go Viewdeos to discuss their docs. Heads up @GeneGenie 

So I'm changing the title of this issue to reflect that it's a docs issue with this one adapter.

**Comment by bretg** [comment]
Docs updated - closing issue. Thanks @GeneGenie
