### ISSUE TITLE
Scrubble with GDPR

### ISSUE THREAD

**Issue by mouchii** [prebid/prebid-server#2002]
Hello,

I would like to better understand the scrubber of Prebid-Server with GDPR.
Could you please explain me why the last digit of IP is set to 0 and some of the geo object was removed if a user accept all the CMP consent ?

Thank you in advance,

**Comment by bretg** [comment]
I suspect the issue is covered in the [Summary of Prebid TCF 2.0 Enforcement](https://docs.google.com/document/d/1fBRaodKifv1pYsWY3ia-9K96VHUjd8kKvxZlOsozm8E/edit#heading=h.1pnyovoljlrm) -- the user needs to **explicitly opt-in** to Special Feature 1 or it "May result in rounding lat/long values and IP address before sending to server-side adapters."

Does this answer the question @mouchii ?

**Comment by bretg** [comment]
@mouchii - I'm going to assume that Special Feature 1 is the answer to your question. Please re-open if necessary.
