### ISSUE TITLE
Defining Account Id on Custom Prebid Server for Prebid Mobile

### ISSUE THREAD

**Issue by GenarC** [prebid/prebid-server#2073]
We are trying to configure a prebid server test environment. Installed all the required components but we have some issues about the configurations. We will use Prebid Mobile and for requests, we need account ids. Where can we define an account id on the server? how to configure and connect DB to our server, we couldn't find any detailed or general information on how to assign an account id for custom prebid servers. Can you help or direct us please.

**Comment by bretg** [comment]
We agree that the startup documentation is lacking. Sorry, it's on the list.

Account IDs are defined by you in the database. See the "replicated database" section of https://docs.prebid.org/prebid-server/hosting/pbs-hosting.html

For PBS-Java, see the `settings.database` items -- https://github.com/prebid/prebid-server-java/blob/master/docs/config-app.md . Example schema and query are in https://github.com/prebid/prebid-server-java/blob/master/docs/application-settings.md -- search for 'account-query'.

It's been a long time since I've set up PBS-Go, but here's what I found:

- Most of the fields in the pbs.yml file have their defaults starting at https://github.com/prebid/prebid-server/blob/b3fea58b934fe160e816c01af48010cff861c291/config/config.go#L632
- I believe the accounts DB info is set in accounts.postgres

But there's no example of the connection info and fetcher query - perhaps @SyntaxNode or @hhhjort can paste an example?

**Comment by mansinahar** [comment]
@GenarC PBS-Go only supports account configs to be provided via the File system and HTTP endpoints today. DB is currently not supported for account configs. You can use the filesystem to provide account configuration by adding the following entries to the pbs.yaml file:
```
accounts:
  filesystem:
    enabled: true
    directorypath:                   // path to where the account configs live on your server
```
Or you can also configure this by setting the `PBS_ACCOUNTS_FILESYSTEM_ENABLED` and `PBS_ACCOUNTS_FILESYSTEM_DIRECTORYPATH` environment variables on your server.

The contents of an example account config JSON file would look something like:
```
{
    "id": "test",
    "name": "test account",
    "disabled": true,
    "cache_ttl": {
        "banner": 600,
        "video": 3600,
        "native": 3600,
        "audio": 3600
    },
    "events": {
        "enabled": true
    }
}

```

**Comment by SyntaxNode** [comment]
@GenarC did the comment from @mansinahar explain how to configure accounts on PBS-Go? We do plan to introduce config docs.

**Comment by GenarC** [comment]
Yes, thank you. We successfully run the PBS. There is a problem with rendering, there are some missing targeting keywords, caused by PUC. I'm working on it.

**Comment by SyntaxNode** [comment]
Looks like this was resolved. If you have further questions, please open a new issue.
