### ISSUE TITLE
Request imp format can generate errors for adapters that don't support a certain format.

### ISSUE THREAD

**Issue by hhhjort** [prebid/prebid-server#2178]
PBS core has a filter step that removes any formats from an imp sent to an adapter that the adapter does not support. This is good, except we also generate an error in the response indicating that an adapter does not support a particular format. This can add unnecessary noise to analytics, in some cases such errors are unavoidable.

For example, adapter A supports banner and native. Adapter B banner only. Publisher has a multiformat imp that supports both banner and native. To avoid the error from being generated for adapter B, the publisher will have to send a banner only request, missing out on any native demand available from adapter A.

I suggest we downgrade this from an error to a warning, or perhaps forgo it completely as long as there is at least one adapter that supports each format supplied. We probably still want an error if there are no adapters able to service a format requested in a request.

**Comment by bretg** [comment]
Got a report that PBS-Java also have an issue in this area. It's not enforcing the mediatype rules at all.e.g. if a bid adapter's config doesn't list 'native', it's not removing imp.native from the request before sending to the adapter. Will open an internal ticket.

**Comment by coreyb-cbs** [comment]
We recently hit this error with one of our bidders (PBS-Java). We pulled the bidder until a resolution is found. To me, it only looks to be an issue if the bidder test checks for unsupported media types. I say this because we have other s2s bidders in play that do not support native but are not producing an error because they do not check for such in their bidder test. Ideally, PBS core would remove unsupported media types from the imp, but to me it looks like the current structure of the imp wouldn't allow this because the media types are not specific to the bidder - they are applied to the slot.

**Comment by bretg** [comment]
@coreyb-cbs - PBS-core makes an adapter-specific version of the ORTB request. It will remove the mediatypes from that copy of the object. Will move that fix up in the priority a bit.

**Comment by coreyb-cbs** [comment]
@bretg following up... was a fix/PR ever created for this?

**Comment by bretg** [comment]
A PBS-Java update is in the works. Would guess it can be released with v1.90. i.e. not the next release (1.89), but the one after.

**Comment by bsardo** [comment]
@AlexBVolcy will be handling this for PBS-Go

**Comment by bretg** [comment]
Released with PBS-Java 1.92

**Comment by SyntaxNode** [comment]
Implemented in PBS-Go 0.228.0.
