### ISSUE TITLE
OpenRTB Support: Filter invalid bids in response

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#225]
Right now the `/auction/openrtb2` endpoints do nothing to validate bids from Bidders.

We should add validation and make sure all the fields required by the OpenRTB 2.5 spec (`id`, `price`, etc) are there, and remove bids which don't define them.

**Comment by hhhjort** [comment]
Is there a possible use case where the Prebid Server consumer (prebid.js?) would want to see potentially invalid bids and do something with them? Only thing that comes to mind is the possibility the spec is relaxed, or a new imp type doesn't used all the currently required fields.

A question of how much server should be validating responses rather than simply being a conduit.
