### ISSUE TITLE
FPD: Merge all bidderconfig ORTB fields into root object while ignoring non-ORTB fields

### ISSUE THREAD

**Issue by bsardo** [prebid/prebid-server#2317]
Issue #2182 focused on how FPD specified in the `bidderconfig.config.ortb2.user.data` and `bidderconfig.config.ortb2.{app/site}.content.data` locations were merged into the root object.

The investigation detailed on this issue resulted in a broader spec change. As a result, all ORTB fields specified in `bidderconfig.config.ortb2.{app/site/user}` should be merged into the corresponding root object and all non-ORTB fields
specified in the bidderconfig should be ignored during the merge.
Furthermore, as part of this change, we should ensure that all arrays are merged by replacement instead of concatenation.

PBS-Go and PBS-Java currently only merge a handful of ORTB fields specified in the bidderconfig into the root object with all other ORTB fields and all non-ORTB fields merging into the root object's `ext.data` field.

We should also be sure to consider ORTB 2.6-specific fields.

**Comment by bretg** [comment]
Thanks for the analysis and issue @bsardo

**Comment by SyntaxNode** [comment]
I've been working in the FPD area of PBS-Go while working on support for DOOH. We can simplify code and improve performance by removing the "non-ORTB fields merging into the root object's ext.data field" requirement.

@bretg Based on your response, that requirement seems like it was a misunderstanding and never existed. To clarify, the expected behavior is any non-ORTB field in the bidder config will be ignored and removed the request. No warnings or errors will be emitted. I believe the spec supports this approach, but doesn't come right out and say it directly.

**Comment by bretg** [comment]
Agreed - made a few updates to the text hoping to clarify. e.g.

```
Bidderconfig.config.ortb2 entries may contain any valid ORTB field.
Any value in bidderconfig.config outside or ortb2 should be ignored.
```

**Comment by bretg** [comment]
Confirmed for PBS-Java
