### ISSUE TITLE
[HELP] User Sync on UK traffic in NYC DC

### ISSUE THREAD

**Issue by mrpbennett** [prebid/prebid-server#235]
I have a publisher sending us UK traffic using prebid s2s which is hitting our DC in NYC because the traffic is coming from DC in NYC. I have been informed that you might be using MSFT Azure to distribute the servers.

What can I do to see that the publisher is hitting a prebid server in Europe?

**Comment by dbemiller** [comment]
Just to clarify: Is the prebid-server traffic running through `prebid.adnxs.com`?

In Prebid.js the URL is configurable. I think most people do go through `prebid.adnxs.com`, because that's the default, but I know at least a handful of companies have deployed prebid-server on their own domains.

**Comment by mrpbennett** [comment]
@dbemiller I am not sure, I just know that the publisher is running UK traffic through a US DC. Do you know it would be configured to run through EU DC over a US one? 

of course if the publisher has a EU DC

**Comment by dbemiller** [comment]
ok. If there's no special config going on, I'll assume they're going through `prebid.adnxs.com`.

If so, there are no prebid server servers running in Europe at the moment... so I _would_ expect the traffic to route through US East. Given the traffic, Azure turned out to be quite expensive... so it lives on Appnexus' servers in the US right now.

**Comment by mrpbennett** [comment]
Thanks Dave I shall inform the publisher
