### ISSUE TITLE
Add support for additional bid properties: ttl, currency, and netRevenue

### ISSUE THREAD

**Issue by snapwich** [prebid/prebid-server#237]
Currently `ttl`, `currency`, and `netRevenue` are not passed through from prebid server, but the prebid server adapter is capable of using them.  This is an issue to track support for those properties.

**Comment by dbemiller** [comment]
Currency was also brought up here: https://github.com/prebid/prebid-server/issues/226

**Comment by hhhjort** [comment]
Now that openrtb passes the whole quest through to the adapters, the adapters have the opportunity to act on them. However if not all adapters support the option in question, then the whole response cannot support it. I see a couple of ways we might handle it.

1. Require bidders to to handle the options, or return no bids if the option exists and they don't handle it. Probably the best solution, but will be hard to enforce without a lot of vigilance. (Who wants to deep dive someone else's adapter to insure currency is handled properly?)
2. Have the adapters advertise which options they support, so all bidders will only get the options that all the other bidders support for  a consistent set of bids.
3. Do nothing, and leave it on the client side what to do about only a subset of bids supporting certain options.

Between 1 and 2, probably depends on what the spec has to say about the options, if they are ignorable by the bidder or not. 3. is the lazy solution of course.

ttl is a bit different, since the ttl should be enforced by prebid server itself, but the adapters may be able to use knowledge about the time constraints they are under. So 3 would seem to be the proper option here.

**Comment by bretg** [comment]
I think we're good on currency now. To cover ttl and netRevenue, I propose we encourage bid adapters to place those values in bidResponse.ext.ttl and bidResponse.ext.netrevenue

**Comment by SyntaxNode** [comment]
> I think we're good on currency now. To cover ttl and netRevenue, I propose we encourage bid adapters to place those values in bidResponse.ext.ttl and bidResponse.ext.netrevenue

Are you suggesting `bidresponse.ext` on the root object or `bidresponse.seatbid[].bid[].ext`? Specifically, the `netRevenue` doesn't make sense to us at the top level.

**Comment by patmmccann** [comment]
TTL now appears covered as well iin the exp field https://github.com/prebid/Prebid.js/pull/5715/files

**Comment by bretg** [comment]
Closing this issue:
- currency supported
- ttl is passed as 'exp' on the response
- netRevenue was solved with the bidadjustments feature
