### ISSUE TITLE
Optimising the account service in go implementation - Why are we always performing patching and merging operation per account request

### ISSUE THREAD

**Issue by ShriprasadM** [prebid/prebid-server#2429]
I can see we can optimise the patch and merge operation done in account service by doing it one time and storing it in the cache. This is already discussed with @mansinahar . We have done the changes and about to raise the PR

Flow what I have understood :
1. fetcher.FetchAccount - returns accountJSON either from backend persistent storage or from cache
2. in Else part : It merges AccountsDefaultsJSON which creates completeJSON
3. setDeriveConfig  - Do something around GDPR
4. Finally we return account object5. 

**Question**: Why are we always performing patching and merging operation of account per request? Shouldn't it be part of cache , where fetcher push the accountJSON  ?

Instead of current Implementation can we have following? I feel it will avoid unnecessary repetitive operation of patch and merge per request

Possibly  the  changes will be expected here
https://github.com/prebid/prebid-server/blob/bdc3190c741bd858b868be21d51a08617e114326/stored_requests/fetcher.go#L213

**Proposed Change:**
>accountJSON := cache.get(account) 
 if   accountJSON == nil {
     accountJSON = fetcher.getAccount() // from backend persistent storage
     /* Have merge and patch logic here*/
     completeJSON = jsonpatch.MergePatch(cfg.AccountDefaultsJSON(), accountJSON)
     accountJSON = completeJSON
     cache.save(accountJSON, ttl)
} 
return accountJSON

**Comment by SyntaxNode** [comment]
We refer to these parts of code as "fetchers". We currently have fetchers for:
- Stored Requests
- Stored Requests - AMP Specific
- Stored Requests.- Video Specific
- Stored Responses
- Account Config
- Category Taxonomy Translations
- TCF GVL (different implementation, same concept)

The fetcher code is 5+ years old and could very much benefit from some attention. A complete refactor is on our radar, but there's a lot going on right now and we haven't been able to devote our time. If you're interested, I'll leave some of our initial design thoughts down below. Not sure when we'll get it, but community contributors are welcomed to work with us (as always) to move it along.

### Q&A

> Why are we always performing patching and merging operation of account per request?

The cache layer currently works on the json data, not the parsed and resolved config object. A more efficient path would be to cache the resolved object. I didn't look into the details of your request, but if you're 100% sure there are no side affects (proven with excellent test coverage) then sure.

> Shouldn't it be part of cache , where fetcher push the accountJSON ?

Yes.

> Instead of current Implementation can we have following? I feel it will avoid unnecessary repetitive operation of patch and merge per request

I'm for simple changes to improve performance. We don't want to accept large changes to the fetcher code since we rather throw it all away and design it better.

### Design Thoughts

We would like to move to a new fetcher design where there are many "sources" (postgres, mysql, http, file system) which return json blobs. The idea is have "source" implementations shared among all fetchers, because right now we have to reimplement them for each new type. This is why you can't use a postgres source for accounts, no one has wanted to do that yet and thus no code exists for it.

The next layer up will be parsing and validation for the specific type of data (stored request, stored response, gvl, etc..). This will have helper code for error handling and perhaps automatic handling for logs and metric reporting.

The top layer (which we'll use to interact with the fetchers) will be the cache. The cache will store fully parsed and resolved objects as well as keep track of errors and not found lookups to give the host control over multiple retries. For example, waiting 5 minutes before looking up an unknown id again. There will be several types of caches offered to be configured by the host and their implementation would be shared between all fetchers. Go now has generics to allow for this.

**Comment by bretg** [comment]
Discussed in backlog meeting - closing.
