### ISSUE TITLE
Google Ad Manager setup guide is obsolete

### ISSUE THREAD

**Issue by clho40** [prebid/prebid-server#2486]
Hello all,

I'm referring to this page [Step By Step Guide to Google Ad Manager Setup](https://docs.prebid.org/adops/step-by-step.html)

The Youtube video is 7-years old and a big part of the UI has changed since then. The provided code snippet is also not supported anymore, GAM will throw an error when using it.
```
<script src = "https://cdn.jsdelivr.net/npm/prebid-universal-creative@latest/dist/creative.js"></script>
<script>
  var ucTagData = {};
  ucTagData.adServerDomain = "";
  ucTagData.pubUrl = "%%PATTERN:url%%";
  ucTagData.targetingMap = %%PATTERN:TARGETINGMAP%%;
  ucTagData.hbPb = "%%PATTERN:hb_pb%%";

  try {
    ucTag.renderAd(document, ucTagData);
  } catch (e) {
    console.log(e);
  }
</script>
```

I have the following question:
1. Coming from mobile apps' perspective, is it really necessary to set up a primary ad server? What was the original intention for such set up?
2. Is there an updated Youtube Google Ad Manager setup guide?

Cheers
CL

**Comment by bretg** [comment]
@clho40 - I'm not sure what you mean by "Youtube video", since Prebid doesn't have any documentation related to youtube.

> Coming from mobile apps' perspective, is it really necessary to set up a primary ad server? What was the original intention for such set up?

I would say 'yes' - header bidding needs ad server line items. Please see our recently updated [Ad Operations Planning Guide](https://docs.prebid.org/adops/adops-planning-guide.html)

> Is there an updated Youtube Google Ad Manager setup guide?

Again, I don't know what you mean by Youtube, but yes, we are actually re-doing the step-by-step GAM setup guide. However, the 

> The provided code snippet is also not supported anymore, GAM will throw an error when using it.

Please let us know what error you're receiving. You should ignore the "Sorry, we don't recognize this tag." error. It will work fine even with that warning.

**Comment by clho40** [comment]
Hello @bretg,

The Youtube video, I am referring to this https://www.youtube.com/watch?v=-bfI24_hwZ0

> I would say 'yes' - header bidding needs ad server line items. Please see our recently updated [Ad Operations Planning Guide](https://docs.prebid.org/adops/adops-planning-guide.html)
When I look at [Prebid Mobile Rendering](https://docs.prebid.org/prebid-mobile/modules/rendering/modules-rendering.html), there are 2 ways to go with:
1. Custom In-App Bidding
2. Prebid Rendering Module with Primary Ad Server

A primary ad server (and line items) are not needed if we go with the "Custom In-App Bidding". Can I assume that the need for a primary ad server are for reporting, and as a fallback measurement, in case all the demand partners do not return any ads?

**Comment by bretg** [comment]
You are quite right to point out that training video is stale, and it's amazing timing. Prebid has just contracted with someone to refresh that and all of the training videos. But that project won't be done until March.

Anyhow, when it comes to mobile line items, this question would have been better in the mobile repo, since this group is focused on server, but I'll take a cut. 

> Can I assume that the need for a primary ad server are for reporting, and as a fallback measurement, in case all the demand partners do not return any ads?

Prebid currently views the "no ad server" scenario as an extreme edge case. There's an example documented for Prebid.js in https://github.com/prebid/Prebid.js/blob/master/integrationExamples/noadserver/basic_noadserver.html .

It's possible the SDK supports a 'no ad server' mode, but again, we would consider that an unimportant edge case for testing purposes because yeah, Prebid is not an ad server. It's not going to help app developers with analytics, fallback, capacity for sponsorships and direct sold, etc. 

If we're wrong about this assumption and the "no ad server" scenario is in fact important, it would be helpful if you could describe your use case in an issue over in https://github.com/prebid/prebid-mobile-ios/issues and let us know what's needed -- including better documentation.
