### ISSUE TITLE
Support analytics modules

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#259]
**Summary:** Prebid Server (PBS) needs to be able to log at a transaction level to support finer-grained analytics. 

**Motivation:** Browsers coming to PBS can have analytics adapters (via PBJS), so are in pretty good shape from a reporting perspective. But mobile requests don't have a way to generate detailed analytics. The best mobile can currently do is the metrics interface, which isn't granular enough for many reporting requirements.

**Definitions:**

* Event - an action requested by a user. There may be multiple events in a given request. e.g. request, adunit-request, bid-request, bid-response, cookie-sync-request, setuid-request.
* Request - the HTTP/S connection from a browser or app.
* AdUnit-Request - the Request from the user may imply that auctions for many AdUnits should be executed
* Bid-Request - each AdUnit-Request may be given to many different bidders. A Bid-Request is specific to an AdUnit+Bidder.
* Bid-Response - each Bid-Request may receive a response from the bidder, or it may not.
* Dimension - an attribute of an event that's useful for analysis. e.g. date, user platform, country, etc.
* Module - a block of code functionality that can be configured to be active on a given installation. e.g. bidder adapters.
* PBS Installation - a cluster of servers running Prebid Server. e.g. AppNexus and Rubicon Project both have PBS Installations available for publishers to utilize. Other pubs may spin up their own installations.

The request is to spec and implement an analytics interface and module system for Prebid Server. Examples of the types of analytics modules that should be possible:

- a module that just logs events to a local file on disk
- a module that does an HTTPS POST to an analytics service
- a module that forwards requests from certain account IDs back to that publisher's data warehouse

**Proposed Requirements:**

1) One or more analytics modules can be configured to run in a given installation of Prebid Server. For example, it may be useful to have one module that logs to a flat file while another samples requests to be forwarded back to the Publisher.

2) Each PBS installation should be able to configure which analytics module(s) should be informed of events. i.e. It should be possible for the same event to be routed to two different analytics modules.

3) Analytics modules should be allowed to have configuration to define things like endpoint, paths, sampling, account scope, or other behaviors.

4) Every Event must be passed to the analytics system. Configured modules may decide whether they care about the Event(s) and how to process it/them. e.g. an analytics module may not care about /setuid events, so may ignore them.

5) Event latency and status (e.g. succeeded, no-bid, timeout) should be passed to the analytics system.

6) All dimensions available to PBS must be available to the analytics modules. Including, but not limited to: 

* datetime
* account
* bidder
* PBS region
* user region
* uidFlag - whether or not this user had an ID in the uids cookie for the given bidder
* bid price
* domain
* referrerUrl
* app ID
* response media type - e.g. display, video
* latform
* timeout value
* sizeDimension
* userAgent
* adUnitCode
* deal ID
* adServerTargeting
* transaction ID
* limit ad tracking flag

7) Analytics modules should be informed when the request is complete and the response sent to the user. This would allow modules delay processing until the outcome of the request is known.

8) It should be possible to inform the Analytics system of arbitrary events. i.e. the list of examples above in the Definition section is not considered exhaustive.

Design Notes:

These requirements don't define how the analytics system API should be structured. It may be called at many points within the Prebid Server code or just at the end of the request after the response has been sent to the user.

**Comment by dbemiller** [comment]
Overall, this looks very sensible to me. I think we're mostly on the same page. +1 especially on composable analytics modules.

Here are some things we should flesh out:

1. In general, how do you think we should handle error cases? For example:

- Go core libs return an error when the Adapter fails to transform their JSON bid params into an object (for whatever reason)
- A Video AdUnit-Request gets sent to a Bidder who doesn't support Video. They make no bid, but it's a publisher error.

Do we log "no bid" events, with nothing to distinguish them? Do we want to catalogue all the possible errors with codes and log those too? Do we log nothing as the bid response?

It'd help to align on an overall strategy, _especially_ if cataloguing the possible errors is a possibility, because it would impact how Bidder code should be written.

2. Requirement (8) _may_ be a problem, depending on what you mean:

> It should be possible to inform the Analytics system of arbitrary events. i.e. the list of examples above in the Definition section is not considered exhaustive.

If you mean "the Analytics system must be extensible, because we may need to add Dimensions and Events in the future," then that makes sense.

If you mean "the Analytics system must be flexible enough that it can handle arbitrary data passed to it," then that's probably a really bad idea.

The former should be true of all good software. The latter... well, I respect the dream, but I don't think it's technically feasible. I've never seen it done effectively, and I've seen a few projects ruined by even trying. Even given my experience, I _still_ don't have an effective way to implement it well. Let me know if you want more details though.

3. I would propose one more requirement:

> Analytics modules should export events in "neutral" data formats (e.g. OpenRTB types, ISO codes, etc).

I think this will help preserve the integrity of the open source code. Host companies who want some custom export format can just fork the project and add their own analytics module to it.

**Comment by bretg** [comment]
Thanks for the input @dbemiller .

> If you mean "the Analytics system must be flexible enough that it can handle arbitrary data passed to it," then that's probably a really bad idea.

I was thinking of a simple approach like events are just strings. Let's say we someday add another module (e.g. ad quality) and that module reports a new custom event (e.g. "rejected creative"). Analytics modules can choose to filter event names or pass them through.

It's there's an issue with weakly-typed events I'm not thinking about, am ok with a more controlled approach where development is required for new events.

> Analytics modules should export events in "neutral" data formats (e.g. OpenRTB types, ISO codes, etc).

This is fine, and agree that modules we write should do this. But such a rule may not apply to others contribute analytics modules.

Errors: how about each event has a status and a statusCode? e.g.  in your first example, the top level "request" could be flagged as status:"error" with statusCode:"parseError".

**Comment by cindyhere33** [comment]
Does this **_rough draft_** align with the requirements?
https://github.com/prebid/prebid-server/blob/analytics_module/analytics/Event.go

@dbemiller I can change the data types as openrtb.BidRequest, etc where I can so we have neutral data types.

Shall develop the parameters to fulfill all (or as many as possible of) the requirements as I go forward.

**Comment by cindyhere33** [comment]
This is what I'm thinking of.

1. On startup, setup and initialize the required analytics modules. 
2. When an endpoint receives a HTTP request, an object is created and sent to these analytics modules.

The question is, when do we log to the modules?

Synchronous logging is pretty straightforward but we might be compromising on performance depending on how many such modules are turned on at the moment. Asynchronous logging can be done by (a) firing off individual go routines to log the object to respective modules, or (b) collecting a few objects and logging at regular intervals of time.  Any thoughts as to how we should do this?

Here is a gist with initial design:
https://gist.github.com/cindyhere33/1f66f2d46fe669a2bbc292921055d6fd

**Comment by ndhimehta** [comment]
cc: @bretg

**Comment by dbemiller** [comment]
oh man... somehow I missed this one.

I will look over it... but I'm on vacation tomorrow, and don't have time to give it the consideration it deserves today. I'll take a look on Monday though.

**Comment by ndhimehta** [comment]
Thanks Dave!

**Comment by dbemiller** [comment]
At a first glance, it looks very good!

**Comment by bretg** [comment]
Great progress. My comments:

1) Does the requirement to add the module into analytics_core.go mean that all analytics modules are always compiled into the server?  This is fine for now, and is no different than the bidder modules, but would be nice to have instructions for how to define the modules at build time.

2) In response to "Should objects be collected and logged at regular intervals of time?" -- my thought was that there would be a "request all done" call that allows analytics modules to batch up each request/response, dealing with the analytics after the server has responded to the client. Of course if analytics is only called once the response has been sent, that would be unnecessary. :-)   For example, say a given request has 3 ad units and 3 bidders on each. We don't want the analytics modules doing their thing and slowing down the user in-between bid responses... we want the whole batch to be processed after the user's timer has stopped.

3) Note that the "graphiteModule" is not meant to be open-sourced. That's a short term hack for us. (Graphite isn't properly an analytics system and could confuse the community if used as an example.) Please use a different example for a second module. e.g. the currently imaginary "rubiconAnalytics" and "analyticsForwardingModule":

```
"analytics": {
      "enabled": true,
      "fileModule": {
            "enabled": true,
            "fileName": "sample_log"
       },
       "rubiconAnalytics": {
            "enabled": true,
            "host": "analytics.rubiconproject.com"
       },
       "analyticsForwardingModule": {
            "enabled":true,
            "accounts": ["11111", "22222"],
            "url":"https://stats.foobar.com/pbs_analytics"
       },
       "analyticsForwardingModule": {
            "enabled":true,
            "accounts": ["33333"],
            "url":"https://data.somewhereelse.com/logstats"
       }
}
```

**Comment by dbemiller** [comment]
### On the Config API

In general, this looks pretty good. I had two nitpicks:

> "enabled": true,

I don't think we need this? If you don't want analytics, you'd just delete the `analystics` key altogether. If `analytics` exists, then it should be used.

> analyticsForwardingModule

You're repeating this key twice... but that won't work, because JSON keys are unique. If you want to define a module which allows multiples, it would have to be something like:

```
"analyticsForwardingModules": [
  {
     "accounts": ["11111", "22222"],
     "url":"https://stats.foobar.com/pbs_analytics"
  },
  {
    "accounts": ["33333"],
    "url":"https://data.somewhereelse.com/logstats"
  }
```

### Implementation

I left some comments on the design gist, because they seemed more relevant there.

Before I can comment on the code gist, I have an open question. I'd normally aim this at the data analyst stakeholders... but since I don't know any of those, @bretg is probably the best go-between.

Question is: Is it better to have _consistent_ data, or _complete_ data?

For example, suppose the PBS app crashes in the middle of the auction. No response ever gets sent.

If we prioritize _completeness_, we would log "an auction started with X,Y,Z bidders," but then send no messages about the corresponding bids.

If we prioritize _consistency_, then we would log nothing at all.

I can imagine some value in both... so some input from the stakeholders would be helpful. If most everyone agrees on an answer, then we can code it that way. If it varies stakeholder-by-stakeholder, then that's a valid answer too.

I'd have different suggestions on how to improve the code depending on the answer.

### Adding on to Bret's comments

> Does the requirement to add the module into analytics_core.go mean that all analytics modules are always compiled into the server? This is fine for now, and is no different than the bidder modules, but would be nice to have instructions for how to define the modules at build time.

I think we should handle the build-time module conversation separately... let's not stress @cindyhere33 out about it too much for this feature.

**Comment by bretg** [comment]
Thanks @dbemiller - I think consistency is the key. Given the volumes that header-bidding can face, I expect some analytics modules to adopt a sampling strategy, which argues against completeness.

**Comment by dbemiller** [comment]
OK, thanks.

I've given this a pretty thorough review for now. I left comments on both the design & code gists assuming that we value consistency more than completeness.

**Comment by cindyhere33** [comment]
Thanks Dave. 

I've responded to your comments with my take on it.  Please review when you can.

**Comment by dbemiller** [comment]
Sounds like you've got a good plan to me ^^.

Feel free to update the gist again, make a PR, or whatever else you think is the best way to keep moving forward
