### ISSUE TITLE
unmarshal of imp.ext.{bidder} fails in dealTier flow after addition of tid field in impression

### ISSUE THREAD

**Issue by AvinashKapre** [prebid/prebid-server#2647]
In the PR: #2412 a mandatory field `tid` was introduced at `imp.ext` due to which  `ReadDealTiersFromImp()` function fails to unmarshal the ext for usecase imp.ext.{bidder} 

i.e: This sample input fails to unmarshal into type `impExt` 
```
"imp": [
    {
        "ext": {
            "appnexus": {
                "dealtier": {
                    "prefix": "apnx",
                    "mindealtier": 4
                }
            }
            "tid": "1234"
        }
    }
]
```
```
// for imp.ext.{bidder}
var impExt map[string]struct {
		DealTier *DealTier `json:"dealTier"`
}
```
**Current behaviour:** `ReadDealTiersFromImp()` returns without dealtier specified in the new location `imp.ext.prebid.{bidder}`.
**Expected behaviour:** As imp.ext.{bidder} is deprecated, we should ignore the unmarhal error for it and proceed to check for dealtier in the new location `imp.ext.prebid.{bidder}`.

Shall I go ahead and submit a fix for the same do we want to support the new field `tid` for deprecated field as well?. I'll update the code accordingly.

**Comment by bsardo** [comment]
Hi @AvinashKapre,

You're correct that there is a problem here as I was able to reproduce the issue. The deal tiers are not being captured from the request due to the presence of the `tid` field or any other primitive type in `imp.ext`.

I'll push up a fix that removes the logic that looks for deal tiers at `imp.ext.BIDDER` since all bidder information at `imp.ext.BIDDER` is migrated to `imp.ext.prebid.bidder.BIDDER` upstream during request validation in `validateImpExt` before `ReadDealTiersFromImp` is executed.
