### ISSUE TITLE
openrtb: support sort_bids

### ISSUE THREAD

**Issue by sandraleon** [prebid/prebid-server#274]
support same sort_bids logic as legacy endpoint.

**Comment by dbemiller** [comment]
hey @sandraleon... could you fill this out with more details?

I looked into this a little while ago, and it's not as straightforward as you might expect. OpenRTB groups the `Bids` by `SeatBid`, whereas the legacy endpoint groups the `Bids` by `Imp`. Since the bucketing is different, it's not clear what "sort" means.

Also: The only motivation I know of for that legacy sort_bids logic was for Mobile. I talked to the Prebid Mobile team when implementing OpenRTB, and they said they didn't need it as long as we attached `targeting` keys _as if_ the bids had been sorted--which we did.

What type of sorting did you intend to add, here, and what's the motivation for it?

**Comment by sandraleon** [comment]
I'm working on adding currency support for the openrtb endpoint. One of the acceptance criteria is to sort the bids correctly based on currency if sort_bids is set to true. We just realized that sort_bids is not supported in the new endpoint. Now that you mention it, it does make sense not to add that since the bids are grouped by seatbids. @bretg should we just leave out that functionality?

**Comment by bretg** [comment]
```
Also: The only motivation I know of for that legacy sort_bids logic was for Mobile.
I talked to the Prebid Mobile maintainers when implementing OpenRTB, and they said they didn't
need it as long as we attached targeting keys as if the bids had been sorted. We implemented it
this way, so that motivation doesn't exist anymore.
```
@dbemiller - what triggers this behavior?

@sandraleon - I have no need for sort_bids -- the aim was to keep up with the moving target. Closing this issue.

**Comment by dbemiller** [comment]
@bretg There isn't really a trigger... it's just the default behavior. If the `bidrequest.ext.prebid.targeting` param exists, then we attach `hb_key` to the winning bids in each Imp. As long as we did that, Mobile said they didn't need the bids to be sorted.
