### ISSUE TITLE
Gofmt failing for not defining package

### ISSUE THREAD

**Issue by oronno** [prebid/prebid-server#2925]
After recent MR https://github.com/prebid/prebid-server/pull/2833 merged, go fmt is failing.  
Run go formatter for all files:
```
gofmt -s -w .
```
Output:
```
.semgrep/adapter/builder-struct-name.go:8:1: expected 'package', found 'func'
.semgrep/adapter/package-import.go:1:1: expected 'package', found 'import'
.semgrep/adapter/package-import.go:3:2: expected ';', found "fmt"
.semgrep/adapter/type-bid-assignment.go:8:1: expected 'package', found 'func'
```

CC: @onkarvhanumante @Sonali-More-Xandr

**Comment by VeronikaSolovei9** [comment]
Yes, this happens due to files nature added to `.semgrep` directory.
To avoid this error the `.semgrep` directory should be skipped in `gofmt` run. Unfortunately `gofmt` is not configurable to this extent. 

To run formatting you can specify directory you want to run it for:
```
gofmt -s -w exchange
```
or specific file:
```
gofmt -s -w exchange/auction.go
```
In order to run gofmt for the entire project, please consider to run `./validate.sh` from the root of Prebid Server project  directory.

**Comment by SyntaxNode** [comment]
Please see the linked issue. We are adding a script to simplify the `go fmt` call while ignoring the appropriate paths.
