### ISSUE TITLE
BidRequest updated by ProcessedAuction hook is getting overridden by requestwrapper utility

### ISSUE THREAD

**Issue by pm-nikhil-vaidya** [prebid/prebid-server#2986]
**Background**
With the introduction of module, hooks have the capabilities to modify the bid request but these modifications are overridden by request wrapper utilities

**Solution 1**
Pass bid request wrapper in the hook payload instead of only bid request object

**Solution 2**
Create a request wrapper with new bid request after each hook execution

**Comment by AlexBVolcy** [comment]
After looking into this I believe that it's true the updates the changeset is making to the bid request is being overwritten by the request wrapper.

Within `auction.go/parseRequest`, the `changeset` is being applied to the base request through this call `hookExecutor.ExecuteRawAuctionStage()`. The base request is then unmarshalled into the request wrapper.

However, before the request wrapper is returned, the wrapper itself is updated through `mergeBidderParams`, `setFieldsImplicitly`, `setDefaults` before `parseRequest` validates and returns. So I think it’s within these functions where the overwrite is occurring

**Comment by hhhjort** [comment]
I think there is some confusion here. In `enndpoints/openrtb2/auction.go:parseRequest`, there is no request wrapper, the modules are operating on raw JSON. We get to a request object and a request wrapper that modules can use in `exchange/exchange.go`. For example: `r.HookExecutor.ExecuteProcessedAuctionStage(r.BidRequestWrapper)`.

Here we are pushing into the hook executor the full bidwrapper. But the payload to the modules is just a plain openrtb2 bid request. The modules then create mutators for the bid request that can be executed to modify the request appropriately. Modifying the `ext`s in the request wrapper requires executing functions rather than just setting values. I am not familiar enough with the mutator system here to know if this can be handled by the mutator system, or if it needs mutators that only set values in structs. If the mutators can handle the wrappers, it would likely take quite a bit of work, and be a breaking change to the module API to push the wrapper into the payload. However the alternative of rebuilding the request wrapper after each module execution would be a significant drain on computing resources.

**Comment by pm-nikhil-vaidya** [comment]
PR https://github.com/prebid/prebid-server/pull/3037

**Comment by bretg** [comment]
This is a documentation issue. @bsardo has offered to update the module developer doc. Thanks!

**Comment by bsardo** [comment]
Closing as there aren't any docs updates needed. The docs don't specify the types of each hook's payload and can be easily determined from looking at the code.
I also confirmed that the request wrapper is part of the payload at both the ProcessedAuction and BidderRequest hook stages.
