### ISSUE TITLE
Need to restore adapter for yeahmobi

### ISSUE THREAD

**Issue by solinary06** [prebid/prebid-server#3194]
I am a member from yeahmobi, and I noticed that yeahmobi adapter has been remove in #3068 , but we are still using the prebid-server for bidding. Could you please help to restore our adapter? You can update the contact email address to mine： steven.liu@yeahmobi.com. thanks you.

**Comment by SyntaxNode** [comment]
> Could you please help to restore our adapter? 

Yes. I hope you saw that the Yeahmobi was only removed because we couldn't reach you at the individual email address. It happens, folks move around. For this reason, we now require a group email address such that our communication is not dependent on a single person still being with the company.

If you could please provide us with a group email address for Yeahmobi, I'll help you with restoring the adapter.

**Comment by solinary06** [comment]
You could use this group email address to contract us: developer@yeahmobi.com
Thank you for the help.

**Comment by SyntaxNode** [comment]
Reverted in PBS-Go 2.0. The adapter was restored before release so its like it was never removed.

**Comment by bretg** [comment]
done with PBS-Java 2.2
