### ISSUE TITLE
prebid.js & prebid server - mapping

### ISSUE THREAD

**Issue by mark34** [prebid/prebid-server#329]
I'm just starting out learning how to use the prebid server so this might be a mad question ;-)

Currently I've got my custom built prebid.js containing the PBserver adapter in my test html page, served locally from localhost:80. There are a couple of ad slots in that test html page. I'm also running the latest (8th Feb 2018) prebid-server locally at localhost:8000.

When I set the s2sConfig line in my javascript to point straight to the PBS auction endpoint : 
``` endpoint: 'http://localhost:8000/openrtb2/auction' ```
the payload sent to the server is not correct for the server. 

I've had to create a mapping endpoint (localhost:80/auction.php) which I use to proxy the request from the client through to my PBS instance (http://localhost:8000/openrtb2/auction), and then map the response back to the client so that the javascript works correctly & the ad is displayed in the page. 
 
Is this really what I have to do, or should I be able to point prebid.js file straight at my prebid-server endpoint http://localhost:8000/openrtb2/auction?

I CURLed a hosted version of the server (https://prebid.adnxs.com/pbs/v1/auction) & saw this is nginx so it's likely they have a web front-end with the prebid server behind that. This leads me to believe that this is the 'right' way to do it. 
 
Can anyone help me out by confirming I'm doing this right(!) or tell me what I should be doing(!)

Ta.

**Comment by dbemiller** [comment]
You're just fine ^^. The `prebidServerAdapter` in Prebid.js is designed to call `/auction` (not /openrtb2/auction`).

So... if you point prebid.js at `/openrtb2/auction` today, I would expect `/openrtb2/auction` to reject it as invalid.

The `prebidServerBidAdapter` in `prebid.js` is being upgraded right now. I opened https://github.com/prebid/Prebid.js/issues/2126 so that you can check up on timelines and follow progress.
