### ISSUE TITLE
Handling Used UUIDs in Prebid Cache

### ISSUE THREAD

**Issue by MiteshVid** [prebid/prebid-server#3379]
The current Prebid cache system effectively removes UUIDs based on the "ttlseconds" mechanism. However, there's a need to discuss how we can manage and automatically remove UUIDs from the cache once they have been used.

Is there a way or any existing mechanism to Remove Used UUIDs from Prebid Cache once it's been used?

**Comment by bretg** [comment]
@MiteshVid - we discussed this in the Prebid Server committee meeting today. We would like to understand your use case -- why is it useful to remove items from cache?

1. We can't remove items by default because it could be a breaking change for some use cases.
2. We could add a query string parameter for publishers that want to force this behavior.
3. This feature could significantly raise the CPU and network utilization between PBC and the backend DB.
4. The testing and verification use case makes being able to do multiple fetches pretty useful.

**Comment by bretg** [comment]
@MiteshVid - any thoughts on the questions from the committee?

**Comment by bretg** [comment]
@MiteshVid - we're going to close this for now. Please explain your use case and we can re-consider. Thanks.
