### ISSUE TITLE
I am building a Bidder. Do I need to build a legacy Adapter?

### ISSUE THREAD

**Issue by muncha** [prebid/prebid-server#340]
I am working on a Bidder for Beachfront Media (beachfront.com). I'm following the documentation [here](https://github.com/prebid/prebid-server/blob/master/docs/developers/add-new-bidder.md). I still need to work on my test cases and a few other things, but, it is working with our endpoint using a POST request similar to what is described [here](https://github.com/prebid/prebid-server/blob/master/docs/endpoints/openrtb2/auction.md). 

My next stage of testing has been to run prebid.js on a test page and have it send requests as described [here](http://prebid.org/dev-docs/get-started-with-prebid-server.html). I'm sending those to openrtb2/auction/, but I get an "id undefined" error. Testing with appnexus instead, it appears to work, but I notice in the example it is using /auction/. Researching that has led me to [the legacy docs](http://prebid.org/dev-docs/add-a-prebid-server-adapter.html) page. I only implemented a Bidder, not the Call() method for an Adapter, as the comments at the top of legacy.go (previously adapter.go) specifically say not to.

The instructions on the legacy Adapter docs say "If you need live server-side support ... you can also follow the steps described on this page." So that sounds like I should implement both in my beachfront.go. 

Before I get into that though, I just wanted to check, should I build an Adapter, or is there some other option?

**Comment by dbemiller** [comment]
Nah. In fact I'd prefer it if you didn't, because it's less code to review & maintain. `Prebid.js` is [adding finishing touches](https://github.com/prebid/Prebid.js/pull/2102) to the PBS adapter, so any legacy code you add will have a very short lifespan.

If you really need legacy support because you can't wait for that PR, or have important publishers can't or won't update to the latest Prebid.js, I'd much rather see a `(Bidder, familyName, usersyncInfo, ???) => Adapter` function which back-ports OpenRTB bidders into Legacy ones. Basically the inverse of [this](https://github.com/prebid/prebid-server/blob/master/exchange/legacy.go#L20), but for maintaining legacy support of new Bidders.
