### ISSUE TITLE
Question: how to port a real time data module (RTD) to prebid-server?

### ISSUE THREAD

**Issue by peczenyj** [prebid/prebid-server#3492]
Hello

This is a question related to #2095 

Currently we have a RTD Module that works fine on prebid.js

https://github.com/prebid/Prebid.js/blob/master/modules/weboramaRtdProvider.js

We receive some questions about Prebid Mobile and how can we integrate our module to it.

If I understand well, the Prebid Mobile is just a client for prebid-server, so I imagine that we need to somehow integrate our module to prebid-server (go ? java ? good question ).

I did not find any suitable example and all RTD modules in prebid.js seems to have no parallel on prebid-server (at least in go).

someone can help me?

Thanks

**Comment by bretg** [comment]
@peczenyj - there's no specific real time data module concept in Prebid Server - everything's just a generic module. See https://docs.prebid.org/prebid-server/developers/add-a-module.html

I'm happy to get on a call to talk about the architecture - bgorsline at at prebid dot dot org

You would want to write the module in the [language](https://docs.prebid.org/faq/prebid-server-faq.html#why-are-there-two-versions-of-prebid-server-are-they-kept-in-sync) most familiar to your engineering team. If either Go or Java is a choice, choose Go because the PBS-Java team ports things from Go-to-Java but not the other way around.

One issue you're going to face is local storage for caching. We're going to discuss this in committee this week.

**Comment by bretg** [comment]
We're in touch via email now so closing this issue. Other vendors interested in exploring a real-time data module are welcome to take the same path.
