### ISSUE TITLE
OpenRTB endpoint to support account id metrics

### ISSUE THREAD

**Issue by mkendall07** [prebid/prebid-server#352]
Currently the ORTB endpoint does not breakout metrics by accountId as the legacy endpoint did.

We should source the account id from either:
`bidrequest.site.publisher.id` or `bidrequest.app.publisher.id`

**Comment by dbemiller** [comment]
Honestly... I don't think this is a good idea. We've been seeing very flaky behavior from Influx recently, and (I believe) this is a major cause for it.

In time-series databases, the number of "measurements" you take [directly affects the hardware you need](https://docs.influxdata.com/influxdb/v1.6/guides/hardware_sizing/#general-hardware-guidelines-for-a-single-node).


When you use an "unbounded" value to form the measurement name, that number explodes. The Prometheus docs [specifically warn against using IDs in labels](https://prometheus.io/docs/practices/naming/#labels). This problem is compounded by the "account X adapter" metrics that the Influx implementation has.

I recognize the Product value... but time-series databases just aren't the right tool for this. The Prebid Host company should build something designed for big data, and then make an Analytics module that writes to it.
