### ISSUE TITLE
go.mod specifies go 1.20, while validation happens on go 1.19

### ISSUE THREAD

**Issue by justadreamer** [prebid/prebid-server#3659]
# Background
go.mod prescribes that the whole project should be compiled with go 1.20 here: https://github.com/prebid/prebid-server/blob/master/go.mod#L3

However validate.yml workflow prescribes running it on go 1.19 here: https://github.com/prebid/prebid-server/blob/master/.github/workflows/validate.yml#L13 - this breaks the expectation of the developers who might have used features available starting go 1.20.  

Also go 1.20 is not supported any more.  1.21 and 1.22 are currently supported versions according to https://endoflife.date/go. 

# Suggested remedy
1. At a minimum validate.yml should be updated (and perhaps other workflows that might still require 1.19) to specify 1.20 and 1.21 (and 1.22).
2. At a maximum requiring go 1.21 in go.mod and updating validate.yml to 1.21 and 1.22 would be ideal.

**Comment by bsardo** [comment]
Hi @justadreamer, this is intentional. PBS-Go currently supports 1.20 and 1.19. The validator intentionally uses the lower version of the two to ensure that we only use features that are supported by both versions. We will be upgrading to the latest version shortly which should alleviate your concerns.

**Comment by SyntaxNode** [comment]
Closing as the behavior is intentional. We'll be updating to Go 1.22 with validation running on Go 1.21 within the next week.
