### ISSUE TITLE
PBC: support a mode that prevents external writes

### ISSUE THREAD

**Issue by bretg** [prebid/prebid-server#3808]
Prebid hosts a PBC server for the test PBS used by the mobile team for testing and examples.

I'd like to clean it up and document it so app developers can make use of the stored requests there, but am hesitant to do so before we lock down the Prebid Cache it uses so no one gets any clever ideas about trying to use it. 

Am asking for a PBC config flag that allows global GET activity, but limits POST activity to PBS. The limit could be IP-address based or key-based.

**Comment by bretg** [comment]
The preference here is to leave this kind of traffic rule with a proxy or load balancer.

**Comment by justadreamer** [comment]
Actually it looks like GCP's load balancer does not allow to block by method, only by headers, paths or port.  AWS seems to allow to block by request method: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/listener-update-rules.html.   Nginx obviously allows to block by request method too. 

So given some load balancers may be limited - it might be desirable to support this restriction in both go and java cache.  Go actually implemented this config feature a while ago, see: 
- https://github.com/prebid/prebid-cache/issues/36
- https://github.com/prebid/prebid-cache/pull/71 (this implements `route.allow_public_write` config)

So with go cache server you can write to the admin port (only exposed to prebid-server) and disable accepting writes from the public port.  I wonder if https://github.com/prebid/prebid-cache/pull/71 has ever been ported to Java or needs to be ported.  Thus this problem is solvable in 2 ways: either if load balancer reverse proxy allows to filter by method or if prebid-cache supports `route.allow_public_write: false` config setting. 

kudos to @YuriyVelichkoPI and @pi-alexander-popel for digging this ^ out.

**Comment by bretg** [comment]
Thanks @justadreamer 

1. This may be doable within AWS load balancers.
2. Will ask the PBS-Java team to look into the admin port feature

**Comment by bretg** [comment]
Canceling this issue. We're just going to port the PBC-Go admin port feature to PBC-Java.
