### ISSUE TITLE
Feature request: Support filtering BidRequest to DSP based on adapter specific Geo country whitelist

### ISSUE THREAD

**Issue by josepowera** [prebid/prebid-server#3898]
With https://github.com/prebid/prebid-server/pull/3887 bidrequest from PBS will always have country (if enabled).

Idea: Adapters could have configuration string with whitelisted geo countrys. 

Why: smaller DSPs are mostly country specific and when PBS does the filtering on single attribute, that would cut bandwidth significantly (from PBS to DSP).

If this is done on bidrequest before specific bid adapter it would be way more generic and would cut boilerplate code significantly (I'm sure nobody in interested in 100 adapters having same code).

If no adapter specific geo country is specified, it should pass all to DSPs (same as currently).

**Comment by bretg** [comment]
@josepowera - assuming that by "DSP" you mean "bidder", this is covered in https://github.com/prebid/prebid-server/issues/2541 

It has been argued the draft requirements for that module is much larger and more complicated than strictly necessary -- it covers many more use cases than just not sending requests to bidders based on the user's country. I would counter-argue that anyone wanting to build this feature could build just the pieces they're interested in and leave the rest of later phases.

Would also like to note that the workaround we've been suggesting is that Prebid-Server host companies and enable and disable bidders for each of their datacenters. For instance, in our cluster, we've only enabled lunamedia in our US datacenters because they asked us to their [YAML file](https://github.com/prebid/prebid-server-java/blob/master/src/main/resources/bidder-config/lunamedia.yaml) declared their 'geoscope' as US.

**Comment by bretg** [comment]
@josepowera - I'm going to assume that https://github.com/prebid/prebid-server/issues/2541 covers your request here. Please re-open with details if there's something in your request not covered there. Thanks.
