### ISSUE TITLE
Multiformat auctions in AMP via RTC [documentation needed?]

### ISSUE THREAD

**Issue by adamleslie** [prebid/prebid-server#408]
Based on the creative asset we execute in the ad server for Prebid via RTC referenced here:

http://prebid.org/adops/setting-up-prebid-for-amp-in-dfp.html

I'm assuming that more than one _mediatype_ is supported through this method, i.e. multiformat auctions outlined here:

http://prebid.org/dev-docs/show-multi-format-ads.html

Question is, how do we configure this in Prebid server?

Specifically interested in a native config currently.

I've reviewed this, but the AMP prebid server configs look slightly different currently:

https://github.com/prebid/prebid-server/commit/73ad79467cd9c5b35dba43e22abb95fd078e8aac

**Comment by dbemiller** [comment]
Prebid Server uses OpenRTB in its API... so the input format is indeed quite different from Prebid.js. Native is supported, although the Appnexus adapter is the only one which supports it.

That said... I think that setup as a whole only supports Banner, because of DFP limitations. I'm not as familiar with DFP as I should be, but I'm told that they require the creative to be a native template... so the creative on the page you linked wouldn't work there.

**Comment by adamleslie** [comment]
Hi,

For the current method in web the native multiformat calls pass additional params into the ad call which point to the elements for the creative template - we then use pattern macros to substitute the endpoints into our template, see the HTML/CSS snippet here:

http://prebid.org/adops/setting-up-prebid-native-in-dfp.html

To realise this in AMP we would need to initialise an auction for these parameters on the Prebid server and set them as key values in the response in a similar way.

I'm happy to give more details if it helps.
