### ISSUE TITLE
Why does this need to be completely separate from prebid.js?

### ISSUE THREAD

**Issue by dumbmatter** [prebid/prebid-server#411]
Please correct me if I'm just being stupid here :)

I understand the utility of prebid.js, it gets you bidding between demand sources with just some simple client side code. Great!

I understand the utility of prebid-server, it gets you the same as prebid.js but runs server side, ["eliminating most of the latency impact that comes with adding more partners"](http://prebid.org/dev-docs/get-started-with-prebid-server.html) and making ["more money without sacrificing user experience"](http://prebid.org/dev-docs/get-started-with-prebid-server.html).

It's my impression that prebid.js has become somewhat of a de facto standard and is very popular right now, but most people using it would ultimately be better off with something like prebid-server. I imagine a reason why some stay on prebid.js is due to broader network support - https://github.com/prebid/Prebid.js/tree/master/modules vs https://github.com/prebid/prebid-server/tree/master/adapters

So my question is, why is prebid-server a completely separate project? Why not have them at least be similar enough to share bid adapters, and maybe even more?

Again, my apologies if this is a stupid question, and thanks in advance for any responses!

**Comment by bretg** [comment]
The two projects are complementary, but quite different.

- PrebidJS must be downloaded by every publisher and runs in the browser. It's javascript. It's job is to collect parameters from the page, package them up, send them off to Prebid Server or an SSP, parse the responses, allow the ad server to collect the results and display winning ads. All of these functions are needed even when Prebid Server is used on the backend.

- Prebid Server has to be hosted, so will be downloaded by many fewer entities. It does a smaller number of functions -- really just injecting a few arguments into the request stream and forwarding them to the SSPs, then back to PrebidJS or PrebidSDK for display.

You can't use Prebid Server without PrebidJS or PrebidSDK.

It would be nice if there was a programming paradigm that would allow us to port the 100+ PrebidJS adapters over to the server environment, but unfortunately that's not currently possible. And in many cases, the server-to-server API is different -- based on OpenRTB instead of a simple URL GET/POST.

HTH.
