### ISSUE TITLE
Bid responses with no bid.crid are considered invalid

### ISSUE THREAD

**Issue by BZSky** [prebid/prebid-server#427]
Hey @hhhjort ! 

Adform Ad Exchange team here. We noticed that adform adapter stopped bidding via prebid server, and traced the cause to this change: #414, this [line](https://github.com/prebid/prebid-server/commit/80df47d81f87a067c4157d9273c160bd740709c7#diff-10ec7da6b0773feb6597ff9d264d0222R363). 

Our Ad Server does not yet support sending **bid.crid**, thus prebid server considers all our bids as invalid currently. 
What is the reason behind validation by **bid.crid**, considering that it is an optional field according to OpenRTB standard? 
Can we at least temporarily remove this check?

**Comment by BZSky** [comment]
@mkendall07 Thanks a lot!

**Comment by dbemiller** [comment]
PR to revert this temporarily is in #432.

Please note that we _do_ have to require this, though. Since Prebid.js requires it, there's no way for the `prebidServerBidAdapter` to convert PBS bids into Prebid.js ones unless we also require it from Bidders in this project.

We'll schedule this as a breaking change which will take effect again in early May.

**Comment by hhhjort** [comment]
The requirement has been rolled back. Adform bids are being processed as valid again, however the prices coming through seem very high.

**Comment by ptomasroos** [comment]
It’s because of local currency @hhhjort but as long as this is handled in the ad server is all right until currency support

**Comment by dbemiller** [comment]
Closing this again because it's been finally merged now.
