### ISSUE TITLE
Possible Data Leakage Through AMP Load Cookie iFrame

### ISSUE THREAD

**Issue by gramorris** [prebid/prebid-server#490]
Just checking on this. It seems that the AMP Cookie Sync iFrame is loading against all possible bidders irrespective of whether they're being used on the page. In the two examples below e-planning and conversant are dropping cookies despite not being bidders.

This would breach GDPR where the data is neither being used and presumably consent would not have been received to do this.

I don't know if it's possible but it would seem that the possible solution may be to pass bidders through to the cookie sync in url vars. If my observations are correct.

<img width="1237" alt="screen shot 2018-05-02 at 18 01 49" src="https://user-images.githubusercontent.com/6436641/39537935-0006f688-4e33-11e8-9737-af06bb32132e.png">
<img width="1238" alt="screen shot 2018-05-02 at 18 01 11" src="https://user-images.githubusercontent.com/6436641/39537936-00259124-4e33-11e8-98fc-7bfd7a588271.png">

**Comment by dbemiller** [comment]
That's a really good catch!

@jaiminpanchal27, @mkendall07, @jsnellbaker ... thoughts?

**Comment by mkendall07** [comment]
it looks like AMP is integrating some kind of consent framework. We'll need to look into that and see if it's possible to pass consent data into PBS. https://github.com/ampproject/amphtml/issues/13716

**Comment by dbemiller** [comment]
@gramorris I'm not a GDPR expert, so... a question about this:

> I don't know if it's possible but it would seem that the possible solution may be to pass bidders through to the cookie sync in url vars. If my observations are correct.

I thought that GDPR required users to give their consent to _each company_ who wanted to use their personal info. If we used query string params for bidders, how would the publisher [setting up their AMP page](http://prebid.org/dev-docs/show-prebid-ads-on-amp-pages.html#amp-content-page) know which bidders the user had consented to?

**Comment by gramorris** [comment]
Yeah you're right, that doesn't satisfy GDPR.

On the consent flags in the amp implementation I don't think that's fit for purpose yet. We've just got to the testing stage now but I don't think there's the ability (there should be and hopefully will be) to get optional consent for multiple vendors and have separate consent flags for each.

Google are selling the AMP solution so I'm assuming they intend to have it complete at some point.

**Comment by dbemiller** [comment]
So... I may have spoken too soon. This may be possible, although we will depend on https://github.com/ampproject/amphtml/issues/14877

According to the [AMP consent docs](https://www.ampproject.org/docs/reference/components/amp-consent), we could get publishers to do:

```
{
  "consents": {
    "prebid-appnexus": {
      "checkConsentHref": "https://some.prebid.com/openrtb2/amp_consent",
      "promptUI": "consent-ui"
    },
    "prebid-pubmatic": {
      "checkConsentHref": "https://some.prebid.com/openrtb2/amp_consent",
      "promptUI": "consent-ui"
    }
    // ... other bidders from your Auction here
  }
}
```

On PBS, `/openrtb2/amp_consent` would receive `POST` messages like this:

```
{
  "consentInstanceId": "prebid-pubmatic"
}
```

One open question I have is: Should the decision of whether or not to require consent be left to the PBS host, or the Bidder? My understanding is that the PBS host would be on the hook legally, since it's hosted in their domain.

In either case, though, this gives us enough info to work with. If it's a PBS-host concern, we could add it to the App config. If it's a Bidder concern, we could add something to the `Usersyncer` and use the `prebid-{bidder}` naming convention to decide whose Usersyncer to call.

----------------------------------------------------------------------------

This would populate the AMP ecosystem with bidder-specific consent. Once those are made available to `amp-iframe` elements, @jaiminpanchal27 could update that script to do a `/cookie_sync` call only for the allowed Bidders. We would also have to update the `/cookie_sync` endpoint to take the bidders as an argument, of course.

------------------------------------------------
I believe this would buy us "MVP" GDPR cookie sync compliance... but I see two warts in the strategy:

1.  Publishers would need to keep their `amp-consent` tags in sync with the Bidders used by their Stored Request. This may be inconvenient for pubs since AdOps usually manages the Stored Request data, and Engineering manages the code on the page. If the two fall out of sync, you may see worse cookie sync rates.

2. The `cookieSync.js` script has no good way to identify which `prebid-{bidder}` keys exist. It would either have to call `GET /info/bidders` on the PBS instance, which would have lousy performance, or we would have to hardcode the list into the JS and keep the two in sync.

I'll keep thinking about it, but... let me know if you have any other thoughts, concerns, or suggestions.

**Comment by dbemiller** [comment]
I was researching stuff for #501 (similar issue in non-AMP pages), and found that the IAB defines a spec for CMPs. These manage consent data across pages, and have some standards for use in iframes:

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#how-can-callers-determine-if-there-is-a-cmp-present-

https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/CMP%20JS%20API%20v1.1%20Final.md#how-can-vendors-that-use-iframes-call-the-cmp-api-from-an-iframe-

If there's some way to load your CMP onto an AMP page and we can find a way to get the consent info into it, this would be a much better solution.

**Comment by jasti** [comment]
@dbemiller, Vamsee from the AMP team here. 

>  It would then be up to the Publisher to make sure they include any Bidders who they drop cookie syncs for in their consent UI.

This is exactly the assumption under which <amp-consent> is currently developed. Having said that we are looking at supporting per vendor, per purpose based consent post May 25th if that's something publisher absolutely request.

**Comment by gramorris** [comment]
@dbemiller @jasti 

Thanks I'll close this, in the immediate term with the amp-consent limitations I'd accept this as the solution. We have a non-optimal solution to ensure we have some level of consent on AMP pages.
