### ISSUE TITLE
Add an endpoint exposing binary revision

### ISSUE THREAD

**Issue by benjaminch** [prebid/prebid-server#559]
Hello guys,

I was wondering if there was any plan to support an eventual endpoint exposing the binary revision on a given running server?
It would help to know on which revision the current server is running.

Maybe just having a `/version` returning a HTTP 200 with a content like `revision: commit sha1`.

What do you think?

If it's ok for you, I'll push a PR implementing so.

Thanks !

**Comment by dbemiller** [comment]
Yeah, a similar idea has definitely crossed my mind before. No solid plan, though.

Can you describe the use-case(s) and the general approach you planned to use to implement it? I suspect there are some serious tradeoffs here depending on the goals and design.

**Comment by benjaminch** [comment]
Yeah sure !

So the main use-case I have in mind is the ability to have several instances of prebid server running in house mainly for integration testing. On our side, we will have: one dev, one preprod and one production server.
While the prod will be mirroring the prebid-server latest release, preprod would most likely host our own master branch (eventually our release) and the dev one will have the latest commit from our dev branch.

Having such setup allow us to have proper integration tests and prevent us from any eventual regressions.

Being able to know which banary version is executed on a given server would be very convenient not to have to look at the binaries on the server nor in logs but just ping `/version`.

Regarding the implementation, I was thinking of sonething really simple:
- At building time, inject into the binary the current git revision as a simple string (via the builtin go build feature allowing so `go build -ldflags "-X main.Rev=`git rev-parse --short HEAD`"`
- Inject this revision to a new endpoint `RevisionEndpoint` which  will simply returns once called via `/version` the current revision with this format: `revision: sha1`. If the revision wasn't injected at build time, simply return `revision; not-set`.

Here is a first draft to do so:
- RevisionEndpoint : https://github.com/criteo-forks/prebid-server/commit/314fc894b3b6df324a5b911c45da388993596da7
- Adding this new endpoint to the server : https://github.com/criteo-forks/prebid-server/commit/2ba3e916c6192437ed20736be6c38867110582cb

Let me know if it makes sense !

**Comment by dbemiller** [comment]
gotcha. Yeah... that's about how I imagined it going.

I do think we can support this workflow... but I'd suggest two changes, if they work for you:

--------------------------------------
Could you add it to the server running on `admin_port`, rather than the main one?

Motivations:

1. Since anyone can easily compile any version with any `-ldflags`, it's quite fragile. I'd rather that publishers didn't learn about this endpoint and believe they could trust it.

2. This keeps our API's surface area smaller, which is good for project maintenance. Since your use-case is a dev one, we don't need to expose it to publishers.

--------------------------------------
Could it return JSON, YAML, or some other standard, machine-readable format?

Motivations:

1. I could easily imagine `/version` returning the latest `git tag` someday as well... so this would be more extensible moving forward

2. Rigorous/standard formats are generally easier to write tooling around.

--------------------------------------
Let me know what you think.

**Comment by benjaminch** [comment]
Actually, it makes perfect sense !
I'll draft something following what you described !

Thanks

**Comment by benjaminch** [comment]
Hello @dbemiller, 

I started to work on this one, but I might need a bit of help. I think I don't really understand where the admin endpoints are set (not sure there are already?). Would it be possible to point me where a new admin endpoint is supposed to be plugged? Maybe there is an existing one that I am missing.

Thanks !

**Comment by benjaminch** [comment]
oh ! Thanks @dbemiller !

**Comment by benjaminch** [comment]
So was I right saying that as of today, no endpoints are registered on the admin port?

**Comment by dbemiller** [comment]
Correct. Or at least, we don't define any explicitly in the code. `pbs_light.go` does import `pprof`, so it does have all the performance-monitoring endpoints on it. https://golang.org/pkg/net/http/pprof/

So when you add your endpoint, we'll want to make sure those are still accessible too.

**Comment by benjaminch** [comment]
Hey @dbemiller, here we go with a first draft. Let me know what do you think.
I double checked that the pprof endpoints were still reachable via the admin port.

**Comment by dbemiller** [comment]
This was fixed by #577. Closing.
