### ISSUE TITLE
assign specific imp.banner.format sizes to specific bidders in ortb request

### ISSUE THREAD

**Issue by jsnellbaker** [prebid/prebid-server#612]
Currently when an ortb request is made to prebid-server; it's structured like the following:
```
...
"imp":[{
  "id":"/19968336/header-bid-tag-0",
  "ext":{
    "appnexus":{
      "keywords":[{"key":"foo","value":["bar","baz"]},{"key":"fizz","value":["buzz"]}],
      "use_pmt_rule":false,
      "placement_id":10433394
    },
    "rubicon":{
      "accountId":1001,
      "siteId":113932,
      "zoneId":535510
    }
  },
  "banner":{
    "format":[{"w":300,"h":250},{"w":300,"h":300},{"w":300,"h":600}]
  }
}]
...
```

This setup means all the sizes are applied to each bidder.

In Prebid.js, there is functionality (sizeMapping/labels) that would allow different bidders to use different sets or a subset of sizes.  For example, `appnexus` bidder would only want size `[[300, 250]]` whereas the `rubicon` bidder would want sizes `[[300, 250], [300, 600]]` in the same auction for the same adunit.  

Would it be possible to setup a way in the prebid server request to mimic this type of distribution/mapping of sizes to bidders?

**Comment by dbemiller** [comment]
I'm sure it's possible... but I don't think this is a good idea.

To put this into OpenRTB, it would have to go somewhere in the `ext`. We can't _remove_ `banner.format` (or any of the sizes for other formats) from the API... so now sizes would be defined in more than one place. That's never good if you can avoid it. It takes more work to document, adds cognitive overhead for callers, etc.

The amount logic it takes to unpack bidder-specific sizes into OpenRTB requests we pass to each bidder isn't trivial either. Then there's also some performance impact.

All that to say... I think this needs some pretty high value to offset the costs. And to be honest, I'm not sure what that value would be.

If I imagine myself as a publisher, I would look at my site and identify some space to put an ad. I would define some sizes, because I still want my site to look decent. The I would use something like Prebid to run the auction to fill that space.

I can't imagine why I would want one Bidder to see different sizes from another. After I've figured out which space I want to sell... why wouldn't I want every Bidder to have the same information about it?

I spoke with @mjacobsonny too, and he agreed that the use case was weak (and may not even exist at all). So... we don't plan to do this unless there are some really compelling reasons we're not seeing.

**Comment by hhhjort** [comment]
The one use case I can come up with is if a bidder does not support multiple sizes, but just uses the first size presented. This would allow a publisher to specify which size the bidder should use. But in practice it would be a real corner case where a publisher has two or more bidders with this limitation, and because of some quirk in the demand provided it is better to have one size from one bidder, and a second size from a second bidder.

Or a publisher wants to work around the above limitation by setting multiple aliases for the limited bidder, and then forcing each alias to bid a different size.

But in either case, the proper fix is to get the bidder to support multiple sizes. In PBS, it should be easy enough to get the adapter to make multiple requests to cover all the sizes if the bidder itself cannot handle such a request raw. Which is a much better solution than encumbering the API with yet more options to work around technically limited bidders.

**Comment by jsnellbaker** [comment]
Thanks for the feedback; closing this issue/request at this time.
