### ISSUE TITLE
Support Bidder Params which are "one per request"

### ISSUE THREAD

**Issue by dbemiller** [prebid/prebid-server#626]
A few Bidders now have defined params that aren't really "per-Imp" params. Appnexus has `member`, and Pubmatic is adding a `wrapper` param in #624

There may be others too. It might be a good idea to generalize support for bidder params in the `request.ext`, rather than forcing them all to be in the `imp`.

**Comment by PubMatic-OpenWrap** [comment]
This is the approach that we propose to add request specific bidder parameters in the oRTB request. 

Currently, the Ext object in the BidRequest is openrtb_ext.ExtRequest  
 // ExtRequest defines the contract for bidrequest.ext 
type ExtRequest struct { 
  Prebid ExtRequestPrebid `json:"prebid"` 
} 

The proposal is to add another parameter 'BidderParams', which would contain bidder specific data, to ExtRequestPrebid 
// ExtRequestPrebid defines the contract for bidrequest.ext.prebid 
type ExtRequestPrebid struct { 
  Aliases                               map[string]string                json:"aliases,omitempty"
  BidAdjustmentFactors       map[string]float64              json:"bidadjustmentfactors,omitempty"
  Cache                                *ExtRequestPrebidCache  json:"cache,omitempty"
  StoredRequest                  *ExtStoredRequest             json:"storedrequest,omitempty"
  Targeting                            *ExtRequestTargeting        json:"targeting,omitempty"
  Debug                                 int                                      json:"debug,omitempty"
  **BidderParams                  interface{}                          json:"bidderparams,omitempty"**   ==> new parameter 
} 

BidderParams interface would be a map, with key as bidderName and value would be another map containing bidder specific data.  
example:   
**var BidderParams map[BidderName]BidderSpecificParams 
type BidderSpecificParams map[string]interface{}**  
  

Each adapter can/should define what the bidder specific data (BidderSpecificParams) would be in order for them to retrieve that information from the request 
so BidderParams in the request that prebid would receive would look like  
`
"bidderparams": { 
  "adapter1": { 
    "key1": "data specific to key1", 
    "key2": "  { 
      "version": 3.3, 
       "profileid": 1234 
      } 
    }, 
  "adapter2": { 
   "key3": "data specific to key3" 
  }, 
  "adapter2": { 
    "key4": [ 
     "data" 
    ] 
  } 
} 
`

This data can be filtered when the request is split for each bidder so that request that is sent to the adapter only has the data specific to that adapter 

So request going to adapter1 will have  
request: { 
  "ext" : { 
   "prebid": { 
     "bidderparams": { 
        "key1": "data specific to key1", 
        "key2": "  { 
          "version": 3.3, 
          "profileid": 1234 
        } 
      } 
    } 
  } 
} 

  
Request going to adapter2 will have 
request: { 
  "ext" : { 
    "prebid": { 
      "bidderparams": { 
       "key3": "data specific to key3" 
      } 
    } 
  } 
} 

Request going to adapter3 will have 
request: { 
  "ext" : { 
    "prebid": { 
      "bidderparams": {    
       "key4": [ 
          "data" 
        ] 
      } 
    } 
  } 
} 
  

There was no entry for adapter4 in the bidderparams, so request going to adapter4 will have 
request: { 
  "ext" : { 
    "prebid": { } 
  } 
} 

This filtration, of sending only bidder specific data within the request to that specific bidder, can be done in the splitBidRequest function in exchange/utils.go. 

Since each adapter has defined the data structure that they expect, they can retrieve it easily when a request is sent to them and use the data as per their requirement.   

I am not sure about how to validate this bidder specific data yet. One thought is to have the BidderParams structure for each adapter defined in the bidder schema so it can be validated along with all the other request parameters or to have the same standard for everyone where each adapter can have BidderParams as just key/value pairs where the key is a string and value is an array of strings 

  

Please let us know your thoughts regarding this approach. We have done similar changes in our fork to accommodate for request specific bidder data. We can raise a PR and discuss the changes there if that seems like the more appropriate place for this discussion

**Comment by isha-bharti** [comment]
Hi @dbemiller, 

Any comments on the suggested approach?

**Comment by dbemiller** [comment]
@isha-bharti I don't work on this project anymore. You may want to open a new issue, since comments on closed ones may not get seen..
