### ISSUE TITLE
CORS error on version 0.40.0 

### ISSUE THREAD

**Issue by mercuryyy** [prebid/prebid-server#648]
Failed to load http://prebid.adnxs.com/pbs/v1/openrtb2/auction: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://www.mydomain.com' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

Started at 1PM UST Time Aug 6

Please Advise we have 7 bidders on s2s got hit with a big revenue drop until we saw the error. 

@dbemiller

**Comment by dbemiller** [comment]
Looks like this was caused by the `cors` library update: https://github.com/prebid/prebid-server/compare/0.39.1...0.40.0#diff-bd247e83efc3c45ae9e8c47233249f18R225

We rolled back our deployed version, and added some integration tests which run from a browser and make sure we get alerted sooner if it happens again.

For other PBS hosts: don't use version 0.40.0. We'll fix this and release a 0.40.1 patch soon.
