### ISSUE TITLE
Timeouts saved in stored requests aren't being processed

### ISSUE THREAD

**Issue by hhhjort** [prebid/prebid-server#744]
in `endpoints/openrtb2/auction.go`, `parseRequest()` we call `parseTimeout()` before `deps.processStoredRequests()`, which means any timeout listed in the stored request won't be considered when calculating the timeout for this request.

**Comment by josephveach** [comment]
This is not a bug.  The call to parseTimeout() gets the timeout value from the request, if any, in order to create an empty context with a timeout that will be used for the duration of the parseRequest() function.  If there is not timeout value in the request, it uses a default timeout value.  The context is created to prevent long delays while executing processStoredRequests(), and does not interfere with setting any timeout in stored requests.

Investigating this ticket did raise a few possible related minor issues, though:

- Getting to this point in the code consumes time that is apparently not subsequently accounted for (i.e., subtracted from any timeouts in the bid collecting process); thus, in theory, if this code completes in just under timeout period T, then we can consume 2T time before we've received all bids.

- If the stored request has a timeout shorter than the default timeout and no timeout is included in the incoming request, getting through this code can exceed the stored timeout period that should be in effect for the request.  Of course, in such a scenario, there's no way to know the stored timeout until the processStoredRequests() completes.

Both of these issues are probably insignificant if we assume that parseRequest() completes very quickly relative to any timeout because the data it looks up is probably resident in memory.  Perhaps simply adding a comment in the code and/or any relevant documentation could be considered.

**Comment by hhhjort** [comment]
This is true. Thanks for the analysis.
