### ISSUE TITLE
error sending request to prebid-cache, idle connection closed

### ISSUE THREAD

**Issue by kanchika** [prebid/prebid-server#751]
We are using a self-hosted prebid-server with prebid-cache server to serve ads on amp.

Lately, when we started getting too many requests on our server; we started receiving this error( in logs and stdout on restarting server) for almost every request made to the prebid-server

` E1115 12:54:17.600445 19829 client.go:77] Error sending the request to Prebid Cache: Post {prebid-cache-url}: http: server closed idle connection`

**Comment by dbemiller** [comment]
looks like that error comes from here in the Go core: https://github.com/golang/go/blob/97324858513735093a958a585cca6d5fc2780533/src/net/http/transport.go#L483

so... it may be a Prebid Cache issue, rather than a Prebid Server one. Some questions:

- How many queries per second (roughly) does it take before you start seeing this problem? Is the threshold consistent?
- If you play around with the Rate limiting config option on PBC, does it change that threshold? https://github.com/prebid/prebid-cache/blob/master/config/config.go#L92

I wouldn't be surprised if the rate limiting library closed connections immediately once the limit was hit... which sounds like it would cause this problem.
