### ISSUE TITLE
JSON test involving a timestamp

### ISSUE THREAD

**Issue by nealeu** [prebid/prebid-server#774]
I'm working on an adaptor and want to use the JSON tests, however, there is no ability to exclude some fields from comparison.
We have a time field which is set to time.Now().Unix().

Would it be okay for our adapter to depend on github.com/jonboulle/clockwork (and therefore have prebid-server require it) as a way of making this testable?

**Comment by dbemiller** [comment]
Thanks for being thoughtful about the issue :).

I'm a little wary of that library because of https://github.com/jonboulle/clockwork/issues/17 and the fact that development on it is really slow (see how sparse the commit log is).

This is a totally legitimate issue, though, and I could imagine other adapters having a similar one.

Could you just define the stuff you need in place? It doesn't take too many lines of code to make this testable.

```
// In your adapter
type instant interface {
	Now() time.Time
}

// In the adapter_map.go for your live/prod code
type realInstant struct{}
func (_ realInstant) Now() time.Time {
	return time.Now()
}

// In your adapter's test code
type knownInstant time.Time
func (i knownInstant) Now() time.Time {
	return time.Time(i)
}
```

**Comment by nealeu** [comment]
That makes sense.  It's easier to move forwards from that than have to deal with tests failing due to race issues.

**Comment by nealeu** [comment]
@dbemiller I've used your suggestion. Worked fine.
