### ISSUE TITLE
Adding custom variable for /cookie_sync end point

### ISSUE THREAD

**Issue by thomashmc1** [prebid/prebid-server#836]
Hello Prebid server team

is there a way for the client to send in a custom variable(publisherID) into the cookie_sync end point and it construct the user sync url with the given variable?
```
s2sConfig: {
  accountId: '123',
  enabled: true,
  bidders: ['33across'],
  custom_var: "aisin38ndf923", // this is the custom variable
  timeout: 5000,
  adapter: 'prebidServer',
  endpoint: 'http://localhost:8000/openrtb2/auction',
  syncEndpoint: 'http://localhost:8000/cookie_sync'
}
```

Thank you

**Comment by hhhjort** [comment]
The cookie_sync API doesn't allow for any additional data to be passed. I assume this custom variable would be used for only one bidder?

I can see two possible solutions for what I think you are trying to accomplish.
1. Assuming the publisher is running their own instance of PBS, they could configure the relevant sync URL for that bidder to include the desire publisher ID (hardcode the variable into the server)
2. Since you reference `s2sConfig`, I assume you are using prebid.js to call PBS from the client side. The `/cookie_sync` endpoint returns the usersync pixels that prebid.js needs to call to make the syncing happen. You could modify the javascript to check these URLs, and modify the URL as needed.

Or if this is going to become a more common use case, you can submit a PR to either project to implement setting the publisherID in the usersync URL.

**Comment by thomashmc1** [comment]
Thank you for the response, the publisher is using the AppNexus host solution, which they can't modify the pbs.json file.
in term of solution #2, do you know if there's a callback that will fire when when /cookie_sync return the response?

Thank you

**Comment by hhhjort** [comment]
I am not as familiar with the prebid.js side of the code, you might want to open an issue on that project to get the best eyes on it.

What bidder takes publisherID as an option on usersync? If there is a big enough use case, someone might take up adding the functionality to PBS ... though it will still need prebid.js changes to have prebid.js send the parameter.

**Comment by bretg** [comment]
@thomashmc1 - is this covered by https://github.com/prebid/Prebid.js/pull/3643 ?

**Comment by thomashmc1** [comment]
yes, thank you! this issue can be closed
