### ISSUE TITLE
Bidder adapter monitoring 

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#890]
Hi @hhhjort,

I would like to know whether Prebid has any monitoring tool to monitor bidder adapter?

**Comment by smithaammassamveettil** [comment]
How do we troubleshoot any prebid related issues in our adapter or in general? Is there any chance of downtime for Prebid server? How do bidders know about it? What is the turn around time in those kind of scenarios? How do we contact you other than raising issue here? Any way to check logs or monitor behaviour?

**Comment by hhhjort** [comment]
That depends in part on the hosting company, especially for down time. We do have metrics for imps bid/nobid/bad input per adapter, but it can be hard to pin any behavior down, since no bids can simply be no advertisers interested in poor inventory, and bad input can simply be publisher error.

Generally debugging would start from the publisher side when they don't see the results expected from their prebid setup. Setting the test flag in the request will cause prebid to include the http calls to the bidders, and the bidder's responses to those calls. This would be the best way to pin down bad bidder behavior.

**Comment by smithaammassamveettil** [comment]
"We do have metrics for imps bid/nobid/bad input per adapter" - Is it accessible for bidders? Can we see brightroll adapter's metrics?

**Comment by smithaammassamveettil** [comment]
Is there a point of contact for server downtime issues? How do we know if there is any down time?

**Comment by hhhjort** [comment]
For the appnexus hosted instance of PBS, https://help.appnexus.com/s/ might be the best route. I don't know about other hosts. The metrics are internal only unfortunately. you could send a prebid request to http://prebid.appnexus.com/pbs/v1/openrtb2/auction to verify that the servers are up.

**Comment by smithaammassamveettil** [comment]
what is Prebid server's latency to route the bid request back and forth?

**Comment by hhhjort** [comment]
In Singapore I see ~ 300 ms for beachfront. This is the time from handing off the request to the beachfront adapter til it comes back with bids, so the round trip to your bidder plus however long it took your bidder to make its bids.In New York this morning I am seeing it vary across 100ms-250ms, and only 130ms in Amsterdam. These latencies I am quoting are the p75 measurements, which means 75% of requests come in under this time.

**Comment by bretg** [comment]
We discussed this today in the Prebid.org Prebid Server meeting. We agree with hhhjort here -- bidders that have questions about performance in the context a given Prebid Server instance should contact the owner of that instance.
