### ISSUE TITLE
Bid request extension

### ISSUE THREAD

**Issue by smithaammassamveettil** [prebid/prebid-server#909]
Hi @hhhjort,

Noticed that every bid request coming from Prebid to our DSP is having the below extension
"ext":{"prebid":{"aliases":{"districtm":"appnexus","appnexus-video":"appnexus"}}

Would like to know what is this for?

Thanks
Smitha

**Comment by hhhjort** [comment]
Note: this applies specifically to the Appnexus hosted instance of prebid. Other instances can be configured differently.

These define aliases, that is a publisher can access an adaptor through a custom name rather than the canonical name. In our instance of PBS, we have added 2 aliases by default for the convenience of our clients, "districtm" and "appnexus-video"

**Comment by bretg** [comment]
@smithaammassamveettil - there are other fields in `ext.prebid` that may come through. Is this something that causes issues on the part of DSPs? We would need to ask each server adapter to suppress `ext.prebid` from their outgoing requests.

**Comment by smithaammassamveettil** [comment]
Asked to know what is its use. As of now, didnot cause any issues to our DSP.
