### ISSUE TITLE
Dockerfile go version

### ISSUE THREAD

**Issue by didil** [prebid/prebid-server#981]
Is there any particular reason why the Go version used in Dockerfile  is 1.11.x and not the latest 1.12.x ?

**Comment by mansinahar** [comment]
I believe it was because there was a bug noted for Go 1.12 in Ubuntu as mentioned here: https://github.com/golang/go/wiki/Ubuntu/f174c92b5fd2dd25c2571cea522f8d2b5b348921#bug-noted-in-ubuntu-golang-112-go-release but looks like it has now been resolved. @didil Would you wanna go ahead and open up a PR for 1.12?

**Comment by didil** [comment]
great ill open a PR tomorrow then

**Comment by mansinahar** [comment]
Cool. Thanks @didil!
