### ISSUE TITLE
Info -Bidder Name endpoint returns a 404 for adapters that are disabled by default.

### ISSUE THREAD

**Issue by oath-jac** [prebid/prebid-server#988]
Our VerizonMedia is disabled by default, it is shown in the bidders endpoint.
It is shown here http://prebid.org/dev-docs/prebid-server-bidders.html
But the bidder detail endpoint returns a 404 because the adapter is disabled.

We expect the adapter details to be available no matter if the adapter is disabled or not.

Thanks

**Comment by benjaminch** [comment]
Hey @oath-jac 

Just to be sure, which endpoint exactly is returning a 404?
I think you are referring about the one on the server directly not the link generated from prebid doc right? (https://github.com/prebid/prebid-server/blob/master/static/bidder-params/verizonmedia.json) 

Thanks

**Comment by oath-jac** [comment]
The endpoint GET /info/bidders lists our verizonmedia adapter but the
GET /info/bidders/{bidderName} does not work because our adapter is disabled by default. If it is enabled the endpoint works.
Because this endpoint does not work, you can't see the details of the adapter on this page http://prebid.org/dev-docs/prebid-server-bidders.html

Thanks

**Comment by benjaminch** [comment]
Hey @oath-jac,

Thanks for clarifying !
I can get the first stab on this one ;)

**Comment by benjaminch** [comment]
Hey @oath-jac just pushed a PR fixing it. I'll let maintainers check it and merge it if it's ok for them :)

**Comment by oath-jac** [comment]
Thanks

**Comment by hhhjort** [comment]
I am not user the info needs to be available if the bidder is disabled. The initial reason for pruning the list is so that automated systems can discover what adapters an install of PBS supports. If the API does not reflect what the install actually supports, then you have to manually keep the list of bidders in whatever config management system you are using in sync with the list of bidders that is enabled in your PBS instance. Also makes it more difficult if someone wants to create a config management system that is portable between independent instances of PBS.

I am open to arguments that disabled bidders be advertised, but for now this is the logic I have.

**Comment by benjaminch** [comment]
Hi @hhhjort,

I understand your points which make sense.
But in that case either bidder shouldn’t be listed into the bidders info list or return the information that the bidder is disabled into the detail section.
As of today I have the feeling that the API is not coherent since disabled bidders are listed.

Cheers

**Comment by hhhjort** [comment]
That is a good point. The two lists should definitely be in sync. So `info/bidders` returns disabled bidders, but `info/bidders/<bidder>` does not? My feeling is ideally `/info/bidders` should be trimmed to match.

**Comment by benjaminch** [comment]
Yes exactly and it’s generating a 404 on http://prebid.org/dev-docs/prebid-server-bidders.html. Si either we don’t expose disabled bidders buys that’s a shame and imo. So either details for disabled bidders are shown and we state that the bidder is disabled, or we can either add an endpoint for disabled bidder or a specific param filter to pick either all, enables or disabled bidders.
But I really think it’s cool to give the opportunity to disabled bidders to be listed so people can request activation.

**Comment by hhhjort** [comment]
If we expose the disabled bidders, we will definitely need a disabled flag for automation to use.

**Comment by benjaminch** [comment]
I am just talking about the info endpoint though no endpoint we can use to bid.
In y case having a flag is definitely a must have in any case.
If you have idea to address this issue I will be happy to work on it ;)

**Comment by hhhjort** [comment]
I am good with either not listing disabled bidders at all, or putting a flag in the particular bidder infos to indicate the bidder is disabled.

**Comment by benjaminch** [comment]
This one should be fixed by now, @oath-jac can you confirm there is no more 404 on the following: http://prebid.org/dev-docs/prebid-server-bidders.html ? 
Thanks

**Comment by oath-jac** [comment]
Confirmed. 

Thanks for the fix!
